/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

namespace custom
{

namespace FIX44
{

enum class BusinessRejectReason
{
    OTHER=0,
    UNKNOWN_ID=1,
    UNKNOWN_SECURITY=2,
    UNSUPPORTED_MESSAGE_TYPE=3,
    APPLICATION_NOT_AVAILABLE=4,
    CONDITIONALLY_REQUIRED_FIELD_MISSING=5,
    NOT_AUTHORIZED=6,
    DELIVER_TO_FIRM_NOT_AVAILABLE_AT_THIS_TIME=7
};

} // namespace FIX44
} // namespace custom