/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

namespace custom
{

namespace FIX44
{

enum class ExecRestatementReason
{
    GT_CORPORATE_ACTION=0,
    GT_RENEWAL=1,
    VERBAL_CHANGE=2,
    REPRICING_OF_ORDER=3,
    BROKER_OPTION=4,
    PARTIAL_DECLINE_OF_ORDER_QTY=5,
    CANCEL_ON_TRADING_HALT=6,
    CANCEL_ON_SYSTEM_FAILURE=7,
    MARKET=8,
    CANCELED=9,
    WAREHOUSE_RECAP=10,
    OTHER=99
};

} // namespace FIX44
} // namespace custom