/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace ExecType
{
    static inline constexpr char NEW='0';
    static inline constexpr char DONE_FOR_DAY='3';
    static inline constexpr char CANCELED='4';
    static inline constexpr char REPLACED='5';
    static inline constexpr char PENDING_CANCEL='6';
    static inline constexpr char STOPPED='7';
    static inline constexpr char REJECTED='8';
    static inline constexpr char SUSPENDED='9';
    static inline constexpr char PENDING_NEW='A';
    static inline constexpr char CALCULATED='B';
    static inline constexpr char EXPIRED='C';
    static inline constexpr char RESTATED='D';
    static inline constexpr char PENDING_REPLACE='E';
    static inline constexpr char TRADE='F';
    static inline constexpr char TRADE_CORRECT='G';
    static inline constexpr char TRADE_CANCEL='H';
    static inline constexpr char ORDER_STATUS='I';
} // namespace ExecType

} // namespace FIX44
} // namespace custom