/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace LastCapacity
{
    static inline constexpr char AGENT='1';
    static inline constexpr char CROSS_AS_AGENT='2';
    static inline constexpr char CROSS_AS_PRINCIPAL='3';
    static inline constexpr char PRINCIPAL='4';
} // namespace LastCapacity

} // namespace FIX44
} // namespace custom