/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace OrderCapacity
{
    static inline constexpr char AGENCY='A';
    static inline constexpr char PROPRIETARY='G';
    static inline constexpr char INDIVIDUAL='I';
    static inline constexpr char PRINCIPAL='P';
    static inline constexpr char RISKLESS_PRINCIPAL='R';
    static inline constexpr char AGENT_FOR_OTHER_MEMBER='W';
} // namespace OrderCapacity

} // namespace FIX44
} // namespace custom