/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

namespace custom
{

namespace FIX44
{

enum class OrdRejReason
{
    BROKER_CREDIT=0,
    UNKNOWN_SYMBOL=1,
    EXCHANGE_CLOSED=2,
    ORDER_EXCEEDS_LIMIT=3,
    TOO_LATE_TO_ENTER=4,
    UNKNOWN_ORDER=5,
    DUPLICATE_ORDER=6,
    DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER=7,
    STALE_ORDER=8,
    TRADE_ALONG_REQUIRED=9,
    INVALID_INVESTOR_ID=10,
    UNSUPPORTED_ORDER_CHARACTERISTIC=11,
    INCORRECT_QUANTITY=13,
    INCORRECT_ALLOCATED_QUANTITY=14,
    UNKNOWN_ACCOUNT=15,
    OTHER=99
};

} // namespace FIX44
} // namespace custom