/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace OrdType
{
    static inline constexpr char MARKET='1';
    static inline constexpr char LIMIT='2';
    static inline constexpr char STOP='3';
    static inline constexpr char STOP_LIMIT='4';
    static inline constexpr char WITH_OR_WITHOUT='6';
    static inline constexpr char LIMIT_OR_BETTER='7';
    static inline constexpr char LIMIT_WITH_OR_WITHOUT='8';
    static inline constexpr char ON_BASIS='9';
    static inline constexpr char PREVIOUSLY_QUOTED='D';
    static inline constexpr char PREVIOUSLY_INDICATED='E';
    static inline constexpr char FOREX_SWAP='G';
    static inline constexpr char FUNARI='I';
    static inline constexpr char MARKET_IF_TOUCHED='J';
    static inline constexpr char MARKET_WITH_LEFT_OVER_AS_LIMIT='K';
    static inline constexpr char PREVIOUS_FUND_VALUATION_POINT='L';
    static inline constexpr char NEXT_FUND_VALUATION_POINT='M';
    static inline constexpr char PEGGED='P';
} // namespace OrdType

} // namespace FIX44
} // namespace custom