/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace Side
{
    static inline constexpr char BUY='1';
    static inline constexpr char SELL='2';
    static inline constexpr char BUY_MINUS='3';
    static inline constexpr char SELL_PLUS='4';
    static inline constexpr char SELL_SHORT='5';
    static inline constexpr char SELL_SHORT_EXEMPT='6';
    static inline constexpr char UNDISCLOSED='7';
    static inline constexpr char CROSS='8';
    static inline constexpr char CROSS_SHORT='9';
    static inline constexpr char CROSS_SHORT_EXEMPT='A';
    static inline constexpr char AS_DEFINED='B';
    static inline constexpr char OPPOSITE='C';
    static inline constexpr char SUBSCRIBE='D';
    static inline constexpr char REDEEM='E';
    static inline constexpr char LEND='F';
    static inline constexpr char BORROW='G';
} // namespace Side

} // namespace FIX44
} // namespace custom