/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace TimeInForce
{
    static inline constexpr char DAY='0';
    static inline constexpr char GOOD_TILL_CANCEL='1';
    static inline constexpr char AT_THE_OPENING='2';
    static inline constexpr char IMMEDIATE_OR_CANCEL='3';
    static inline constexpr char FILL_OR_KILL='4';
    static inline constexpr char GOOD_TILL_CROSSING='5';
    static inline constexpr char GOOD_TILL_DATE='6';
    static inline constexpr char AT_THE_CLOSE='7';
} // namespace TimeInForce

} // namespace FIX44
} // namespace custom