/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cstdint>
#include <cstddef>

#include <llfix/fix_client.h>
#include <llfix/core/utilities/tcp_connector.h>

namespace llfix
{
// Forward declarations
class FixString;
class IncomingFixMessage;
}

namespace custom
{

class MyClient : public llfix::FixClient<llfix::TCPConnector>
{
    public:
        // Entry point invoked by the engine's run loop (no user-side loop required)
        void run() override;

        // Connection lifecycle callbacks
        void on_connection() override;
        void on_disconnection() override;

        // Session logon/logout responses
        void on_logon_response(const llfix::IncomingFixMessage* message) override;
        void on_logon_reject(const  llfix::IncomingFixMessage* message) override;
        void on_logout_response(const llfix::IncomingFixMessage* message) override;

        // Session-level server requests
        void on_server_heartbeat() override;
        void on_server_test_request(const llfix::IncomingFixMessage* message) override;
        void on_server_resend_request(const llfix::IncomingFixMessage* message) override;

        // Application-level inbound messages
        void on_execution_report(const llfix::IncomingFixMessage* message) override;
        void on_order_cancel_replace_reject(const llfix::IncomingFixMessage* message) override;
        void on_application_level_reject(const llfix::IncomingFixMessage* message) override;
        void on_session_level_reject(const llfix::IncomingFixMessage* message) override;
        void on_custom_message_type(const llfix::IncomingFixMessage* message) override;

        // Outbound session requests
        bool send_logon_request() override;
        bool send_logout_request() override;
        bool send_client_heartbeat(llfix::FixString* test_request_id) override;
        bool send_test_request() override;
        bool send_resend_request() override;
        bool send_sequence_reset_message(uint32_t desired_sequence_no) override;
        bool send_gap_fill_message() override;
        bool send_reject_message(const llfix::IncomingFixMessage& incoming_message, uint32_t reject_reason_code, const char* buffer_message, std::size_t buffer_message_length, uint32_t error_tag=0) override;
};

} // namespace