/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include <llfix/engine.h>
#include <llfix/fix_string.h>
#include <llfix/incoming_fix_message.h>
#include "MyClient.h"

namespace custom
{

// Main execution loop of the FIX client (invoked from the engine's run loop, no user-side loop required)
void MyClient::run()
{
    process();
}

// Called when a connection to the FIX server is established
void MyClient::on_connection()
{
}

// Called when the connection to the FIX server is lost
void MyClient::on_disconnection()
{
}

// Called when a successful logon response is received from the server
void MyClient::on_logon_response(const llfix::IncomingFixMessage* message)
{
}

// Called when a logon rejection message is received from the server
void MyClient::on_logon_reject(const llfix::IncomingFixMessage* message)
{
}

// Called when a logout response is received from the server
void MyClient::on_logout_response(const llfix::IncomingFixMessage* message)
{
}

// Called when a heartbeat is received from the server
void MyClient::on_server_heartbeat()
{
}

// Called when a test request is received from the server
void MyClient::on_server_test_request(const llfix::IncomingFixMessage* message)
{
}

// Called when a resend request is received from the server
void MyClient::on_server_resend_request(const llfix::IncomingFixMessage* message)
{
}

// Called when an execution report message is received
void MyClient::on_execution_report(const llfix::IncomingFixMessage* message)
{
}

// Called when an order cancel/replace reject message is received
void MyClient::on_order_cancel_replace_reject(const llfix::IncomingFixMessage* message)
{
}

// Called when an application-level reject message is received
void MyClient::on_application_level_reject(const llfix::IncomingFixMessage* message)
{
}

// Called when a session-level reject message is received
void MyClient::on_session_level_reject(const llfix::IncomingFixMessage* message)
{
}

// Called when a custom or user-defined FIX message is received
void MyClient::on_custom_message_type(const llfix::IncomingFixMessage* message)
{
}

// Handles sending a logon request to the FIX server
bool MyClient::send_logon_request()
{
    return llfix::FixClient<llfix::TCPConnector>::send_logon_request();
}

// Handles sending a logout request to the FIX server
bool MyClient::send_logout_request()
{
    return llfix::FixClient<llfix::TCPConnector>::send_logout_request();
}

// Handles sending a heartbeat message to the server
bool MyClient::send_client_heartbeat(llfix::FixString* test_request_id)
{
    return llfix::FixClient<llfix::TCPConnector>::send_client_heartbeat(test_request_id);
}

// Handles sending a test request message to the server
bool MyClient::send_test_request()
{
    return llfix::FixClient<llfix::TCPConnector>::send_test_request();
}

// Handles sending a resend request message to the server
bool MyClient::send_resend_request()
{
    return llfix::FixClient<llfix::TCPConnector>::send_resend_request();
}

// Handles sending a sequence reset message with the desired sequence number
bool MyClient::send_sequence_reset_message(uint32_t desired_sequence_no)
{
    return llfix::FixClient<llfix::TCPConnector>::send_sequence_reset_message(desired_sequence_no);
}

// Handles sending a gap fill sequence reset message
bool MyClient::send_gap_fill_message()
{
    return llfix::FixClient<llfix::TCPConnector>::send_gap_fill_message();
}

// Handles sending a reject message in response to an invalid incoming message
bool MyClient::send_reject_message(const llfix::IncomingFixMessage& incoming_message, uint32_t reject_reason_code, const char* buffer_message, std::size_t buffer_message_length, uint32_t error_tag)
{
    return llfix::FixClient<llfix::TCPConnector>::send_reject_message(incoming_message, reject_reason_code, buffer_message, buffer_message_length, error_tag);
}

} // namespace