/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "ExecutionReport.h"

namespace custom
{

namespace FIX44
{

ExecutionReport::ExecutionReport(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

ExecutionReport::ExecutionReport(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* ExecutionReport::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void ExecutionReport::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void ExecutionReport::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool ExecutionReport::has_ExecType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(150);
}

char ExecutionReport::get_ExecType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(150);
}

void ExecutionReport::set_ExecType(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(150, val);
}

bool ExecutionReport::has_OrdStatus() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(39);
}

char ExecutionReport::get_OrdStatus() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(39);
}

void ExecutionReport::set_OrdStatus(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(39, val);
}

bool ExecutionReport::has_Side() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(54);
}

char ExecutionReport::get_Side() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(54);
}

void ExecutionReport::set_Side(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(54, val);
}

bool ExecutionReport::has_OrdType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(40);
}

char ExecutionReport::get_OrdType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(40);
}

void ExecutionReport::set_OrdType(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(40, val);
}

bool ExecutionReport::has_TimeInForce() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(59);
}

char ExecutionReport::get_TimeInForce() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(59);
}

void ExecutionReport::set_TimeInForce(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(59, val);
}

bool ExecutionReport::has_OrderCapacity() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(528);
}

char ExecutionReport::get_OrderCapacity() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(528);
}

void ExecutionReport::set_OrderCapacity(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(528, val);
}

bool ExecutionReport::has_LastCapacity() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(29);
}

char ExecutionReport::get_LastCapacity() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(29);
}

void ExecutionReport::set_LastCapacity(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(29, val);
}

bool ExecutionReport::has_HandlInst() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(21);
}

char ExecutionReport::get_HandlInst() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(21);
}

void ExecutionReport::set_HandlInst(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(21, val);
}

bool ExecutionReport::has_PartyIDSource() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(447);
}

char ExecutionReport::get_PartyIDSource() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(447);
}

void ExecutionReport::set_PartyIDSource(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(447, val);
}

bool ExecutionReport::has_OptAttribute() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(206);
}

char ExecutionReport::get_OptAttribute() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(206);
}

void ExecutionReport::set_OptAttribute(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(206, val);
}

bool ExecutionReport::has_OrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(37);
}

std::string_view ExecutionReport::get_OrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(37)->to_string_view();
}

void ExecutionReport::set_OrderID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(37, buffer);
}

bool ExecutionReport::has_SecondaryOrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(198);
}

std::string_view ExecutionReport::get_SecondaryOrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(198)->to_string_view();
}

void ExecutionReport::set_SecondaryOrderID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(198, buffer);
}

bool ExecutionReport::has_SecondaryClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(526);
}

std::string_view ExecutionReport::get_SecondaryClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(526)->to_string_view();
}

void ExecutionReport::set_SecondaryClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(526, buffer);
}

bool ExecutionReport::has_SecondaryExecID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(527);
}

std::string_view ExecutionReport::get_SecondaryExecID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(527)->to_string_view();
}

void ExecutionReport::set_SecondaryExecID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(527, buffer);
}

bool ExecutionReport::has_ClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(11);
}

std::string_view ExecutionReport::get_ClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(11)->to_string_view();
}

void ExecutionReport::set_ClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(11, buffer);
}

bool ExecutionReport::has_OrigClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(41);
}

std::string_view ExecutionReport::get_OrigClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(41)->to_string_view();
}

void ExecutionReport::set_OrigClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(41, buffer);
}

bool ExecutionReport::has_ExecID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(17);
}

std::string_view ExecutionReport::get_ExecID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(17)->to_string_view();
}

void ExecutionReport::set_ExecID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(17, buffer);
}

bool ExecutionReport::has_ExecRefID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(19);
}

std::string_view ExecutionReport::get_ExecRefID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(19)->to_string_view();
}

void ExecutionReport::set_ExecRefID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(19, buffer);
}

bool ExecutionReport::has_Account() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(1);
}

std::string_view ExecutionReport::get_Account() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(1)->to_string_view();
}

void ExecutionReport::set_Account(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(1, buffer);
}

bool ExecutionReport::has_Currency() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(15);
}

std::string_view ExecutionReport::get_Currency() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(15)->to_string_view();
}

void ExecutionReport::set_Currency(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(15, buffer);
}

bool ExecutionReport::has_ExecInst() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(18);
}

std::string_view ExecutionReport::get_ExecInst() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(18)->to_string_view();
}

void ExecutionReport::set_ExecInst(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(18, buffer);
}

bool ExecutionReport::has_LastMkt() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(30);
}

std::string_view ExecutionReport::get_LastMkt() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(30)->to_string_view();
}

void ExecutionReport::set_LastMkt(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(30, buffer);
}

bool ExecutionReport::has_TradingSessionID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(336);
}

std::string_view ExecutionReport::get_TradingSessionID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(336)->to_string_view();
}

void ExecutionReport::set_TradingSessionID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(336, buffer);
}

bool ExecutionReport::has_TradingSessionSubID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(625);
}

std::string_view ExecutionReport::get_TradingSessionSubID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(625)->to_string_view();
}

void ExecutionReport::set_TradingSessionSubID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(625, buffer);
}

bool ExecutionReport::has_TradeDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(75);
}

std::string_view ExecutionReport::get_TradeDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(75)->to_string_view();
}

void ExecutionReport::set_TradeDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(75, buffer);
}

bool ExecutionReport::has_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(58);
}

std::string_view ExecutionReport::get_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(58)->to_string_view();
}

void ExecutionReport::set_Text(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(58, buffer);
}

bool ExecutionReport::has_PartyID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(448);
}

std::string_view ExecutionReport::get_PartyID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(448)->to_string_view();
}

void ExecutionReport::set_PartyID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(448, buffer);
}

bool ExecutionReport::has_Symbol() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(55);
}

std::string_view ExecutionReport::get_Symbol() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(55)->to_string_view();
}

void ExecutionReport::set_Symbol(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(55, buffer);
}

bool ExecutionReport::has_SymbolSfx() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(65);
}

std::string_view ExecutionReport::get_SymbolSfx() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(65)->to_string_view();
}

void ExecutionReport::set_SymbolSfx(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(65, buffer);
}

bool ExecutionReport::has_SecurityID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(48);
}

std::string_view ExecutionReport::get_SecurityID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(48)->to_string_view();
}

void ExecutionReport::set_SecurityID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(48, buffer);
}

bool ExecutionReport::has_SecurityIDSource() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(22);
}

std::string_view ExecutionReport::get_SecurityIDSource() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(22)->to_string_view();
}

void ExecutionReport::set_SecurityIDSource(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(22, buffer);
}

bool ExecutionReport::has_CFICode() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(461);
}

std::string_view ExecutionReport::get_CFICode() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(461)->to_string_view();
}

void ExecutionReport::set_CFICode(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(461, buffer);
}

bool ExecutionReport::has_SecurityType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(167);
}

std::string_view ExecutionReport::get_SecurityType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(167)->to_string_view();
}

void ExecutionReport::set_SecurityType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(167, buffer);
}

bool ExecutionReport::has_SecuritySubType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(762);
}

std::string_view ExecutionReport::get_SecuritySubType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(762)->to_string_view();
}

void ExecutionReport::set_SecuritySubType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(762, buffer);
}

bool ExecutionReport::has_MaturityMonthYear() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(200);
}

std::string_view ExecutionReport::get_MaturityMonthYear() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(200)->to_string_view();
}

void ExecutionReport::set_MaturityMonthYear(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(200, buffer);
}

bool ExecutionReport::has_MaturityDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(541);
}

std::string_view ExecutionReport::get_MaturityDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(541)->to_string_view();
}

void ExecutionReport::set_MaturityDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(541, buffer);
}

bool ExecutionReport::has_CouponPaymentDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(224);
}

std::string_view ExecutionReport::get_CouponPaymentDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(224)->to_string_view();
}

void ExecutionReport::set_CouponPaymentDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(224, buffer);
}

bool ExecutionReport::has_IssueDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(225);
}

std::string_view ExecutionReport::get_IssueDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(225)->to_string_view();
}

void ExecutionReport::set_IssueDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(225, buffer);
}

bool ExecutionReport::has_RepoCollateralSecurityType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(239);
}

std::string_view ExecutionReport::get_RepoCollateralSecurityType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(239)->to_string_view();
}

void ExecutionReport::set_RepoCollateralSecurityType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(239, buffer);
}

bool ExecutionReport::has_CreditRating() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(255);
}

std::string_view ExecutionReport::get_CreditRating() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(255)->to_string_view();
}

void ExecutionReport::set_CreditRating(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(255, buffer);
}

bool ExecutionReport::has_InstrRegistry() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(543);
}

std::string_view ExecutionReport::get_InstrRegistry() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(543)->to_string_view();
}

void ExecutionReport::set_InstrRegistry(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(543, buffer);
}

bool ExecutionReport::has_CountryOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(470);
}

std::string_view ExecutionReport::get_CountryOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(470)->to_string_view();
}

void ExecutionReport::set_CountryOfIssue(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(470, buffer);
}

bool ExecutionReport::has_StateOrProvinceOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(471);
}

std::string_view ExecutionReport::get_StateOrProvinceOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(471)->to_string_view();
}

void ExecutionReport::set_StateOrProvinceOfIssue(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(471, buffer);
}

bool ExecutionReport::has_LocaleOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(472);
}

std::string_view ExecutionReport::get_LocaleOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(472)->to_string_view();
}

void ExecutionReport::set_LocaleOfIssue(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(472, buffer);
}

bool ExecutionReport::has_RedemptionDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(240);
}

std::string_view ExecutionReport::get_RedemptionDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(240)->to_string_view();
}

void ExecutionReport::set_RedemptionDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(240, buffer);
}

bool ExecutionReport::has_StrikeCurrency() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(947);
}

std::string_view ExecutionReport::get_StrikeCurrency() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(947)->to_string_view();
}

void ExecutionReport::set_StrikeCurrency(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(947, buffer);
}

bool ExecutionReport::has_SecurityExchange() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(207);
}

std::string_view ExecutionReport::get_SecurityExchange() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(207)->to_string_view();
}

void ExecutionReport::set_SecurityExchange(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(207, buffer);
}

bool ExecutionReport::has_Issuer() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(106);
}

std::string_view ExecutionReport::get_Issuer() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(106)->to_string_view();
}

void ExecutionReport::set_Issuer(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(106, buffer);
}

bool ExecutionReport::has_SecurityDesc() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(107);
}

std::string_view ExecutionReport::get_SecurityDesc() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(107)->to_string_view();
}

void ExecutionReport::set_SecurityDesc(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(107, buffer);
}

bool ExecutionReport::has_Pool() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(691);
}

std::string_view ExecutionReport::get_Pool() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(691)->to_string_view();
}

void ExecutionReport::set_Pool(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(691, buffer);
}

bool ExecutionReport::has_ContractSettlMonth() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(667);
}

std::string_view ExecutionReport::get_ContractSettlMonth() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(667)->to_string_view();
}

void ExecutionReport::set_ContractSettlMonth(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(667, buffer);
}

bool ExecutionReport::has_CPRegType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(876);
}

std::string_view ExecutionReport::get_CPRegType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(876)->to_string_view();
}

void ExecutionReport::set_CPRegType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(876, buffer);
}

bool ExecutionReport::has_DatedDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(873);
}

std::string_view ExecutionReport::get_DatedDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(873)->to_string_view();
}

void ExecutionReport::set_DatedDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(873, buffer);
}

bool ExecutionReport::has_InterestAccrualDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(874);
}

std::string_view ExecutionReport::get_InterestAccrualDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(874)->to_string_view();
}

void ExecutionReport::set_InterestAccrualDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(874, buffer);
}

bool ExecutionReport::has_Price() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(44);
}

bool ExecutionReport::has_StopPx() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(99);
}

bool ExecutionReport::has_DiscretionPrice() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(845);
}

bool ExecutionReport::has_LastQty() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(32);
}

bool ExecutionReport::has_LastPx() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(31);
}

bool ExecutionReport::has_LeavesQty() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(151);
}

bool ExecutionReport::has_CumQty() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(14);
}

bool ExecutionReport::has_AvgPx() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(6);
}

bool ExecutionReport::has_MinQty() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(110);
}

bool ExecutionReport::has_MaxFloor() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(111);
}

bool ExecutionReport::has_RepurchaseRate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(227);
}

bool ExecutionReport::has_Factor() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(228);
}

bool ExecutionReport::has_StrikePrice() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(202);
}

bool ExecutionReport::has_ContractMultiplier() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(231);
}

bool ExecutionReport::has_CouponRate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(223);
}

bool ExecutionReport::has_OrdRejReason() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(103);
}

bool ExecutionReport::has_ExecRestatementReason() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(378);
}

bool ExecutionReport::has_EncodedTextLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(354);
}

bool ExecutionReport::has_LastLiquidityInd() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(851);
}

bool ExecutionReport::has_NoPartyIDs() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(453);
}

bool ExecutionReport::has_PartyRole() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(452);
}

bool ExecutionReport::has_RepurchaseTerm() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(226);
}

bool ExecutionReport::has_EncodedIssuerLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(348);
}

bool ExecutionReport::has_EncodedSecurityDescLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(350);
}

bool ExecutionReport::has_TransactTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(60);
}

std::string_view ExecutionReport::get_TransactTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(60)->to_string_view();
}

void ExecutionReport::set_timestamp_TransactTime()
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_timestamp_tag(60);
}

bool ExecutionReport::has_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(355);
}

const char* ExecutionReport::get_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(355).data();
}

void ExecutionReport::set_EncodedText(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(355, data, data_length);
}

bool ExecutionReport::has_EncodedIssuer() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(349);
}

const char* ExecutionReport::get_EncodedIssuer() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(349).data();
}

void ExecutionReport::set_EncodedIssuer(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(349, data, data_length);
}

bool ExecutionReport::has_EncodedSecurityDesc() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(351);
}

const char* ExecutionReport::get_EncodedSecurityDesc() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(351).data();
}

void ExecutionReport::set_EncodedSecurityDesc(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(351, data, data_length);
}


} // namespace

} // namespace