/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cassert>
#include <cstdint>
#include <cstddef>
#include <string_view>

#include <llfix/incoming_fix_message.h>
#include <llfix/outgoing_fix_message.h>

namespace custom
{

namespace FIX44
{

class Logon
{
    public:
        explicit Logon(llfix::OutgoingFixMessage*);
        explicit Logon(const llfix::IncomingFixMessage*);

        llfix::OutgoingFixMessage* outgoing_message();

        void set_msg_type(char);
        void set_msg_type(const std::string_view&);

        // ResetSeqNumFlag
        bool has_ResetSeqNumFlag() const;
        bool get_ResetSeqNumFlag() const;
        void set_ResetSeqNumFlag(bool);
        // Username
        bool has_Username() const;
        std::string_view get_Username() const;
        void set_Username(const std::string_view&);
        // Password
        bool has_Password() const;
        std::string_view get_Password() const;
        void set_Password(const std::string_view&);
        // EncryptMethod
        bool has_EncryptMethod() const;

        template <typename T>
        T get_EncryptMethod_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(98);
        }

        template <typename T>
        void set_EncryptMethod(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(98, val);
        }

        // HeartBtInt
        bool has_HeartBtInt() const;

        template <typename T>
        T get_HeartBtInt_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(108);
        }

        template <typename T>
        void set_HeartBtInt(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(108, val);
        }

        // NextExpectedMsgSeqNum
        bool has_NextExpectedMsgSeqNum() const;

        template <typename T>
        T get_NextExpectedMsgSeqNum_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(789);
        }

        template <typename T>
        void set_NextExpectedMsgSeqNum(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(789, val);
        }

        // MaxMessageSize
        bool has_MaxMessageSize() const;

        template <typename T>
        T get_MaxMessageSize_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(383);
        }

        template <typename T>
        void set_MaxMessageSize(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(383, val);
        }

    private:
        llfix::OutgoingFixMessage* m_outgoing_message_instance = nullptr;
        const llfix::IncomingFixMessage* m_incoming_message_instance = nullptr;
};

} // namespace

} // namespace