/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "OrderCancelRequest.h"

namespace custom
{

namespace FIX44
{

OrderCancelRequest::OrderCancelRequest(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

OrderCancelRequest::OrderCancelRequest(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* OrderCancelRequest::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void OrderCancelRequest::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void OrderCancelRequest::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool OrderCancelRequest::has_Side() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(54);
}

char OrderCancelRequest::get_Side() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(54);
}

void OrderCancelRequest::set_Side(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(54, val);
}

bool OrderCancelRequest::has_OrigClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(41);
}

std::string_view OrderCancelRequest::get_OrigClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(41)->to_string_view();
}

void OrderCancelRequest::set_OrigClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(41, buffer);
}

bool OrderCancelRequest::has_OrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(37);
}

std::string_view OrderCancelRequest::get_OrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(37)->to_string_view();
}

void OrderCancelRequest::set_OrderID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(37, buffer);
}

bool OrderCancelRequest::has_ClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(11);
}

std::string_view OrderCancelRequest::get_ClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(11)->to_string_view();
}

void OrderCancelRequest::set_ClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(11, buffer);
}

bool OrderCancelRequest::has_SecondaryClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(526);
}

std::string_view OrderCancelRequest::get_SecondaryClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(526)->to_string_view();
}

void OrderCancelRequest::set_SecondaryClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(526, buffer);
}

bool OrderCancelRequest::has_ClOrdLinkID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(583);
}

std::string_view OrderCancelRequest::get_ClOrdLinkID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(583)->to_string_view();
}

void OrderCancelRequest::set_ClOrdLinkID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(583, buffer);
}

bool OrderCancelRequest::has_ListID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(66);
}

std::string_view OrderCancelRequest::get_ListID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(66)->to_string_view();
}

void OrderCancelRequest::set_ListID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(66, buffer);
}

bool OrderCancelRequest::has_Account() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(1);
}

std::string_view OrderCancelRequest::get_Account() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(1)->to_string_view();
}

void OrderCancelRequest::set_Account(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(1, buffer);
}

bool OrderCancelRequest::has_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(58);
}

std::string_view OrderCancelRequest::get_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(58)->to_string_view();
}

void OrderCancelRequest::set_Text(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(58, buffer);
}

bool OrderCancelRequest::has_EncodedTextLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(354);
}

bool OrderCancelRequest::has_TransactTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(60);
}

std::string_view OrderCancelRequest::get_TransactTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(60)->to_string_view();
}

void OrderCancelRequest::set_timestamp_TransactTime()
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_timestamp_tag(60);
}

bool OrderCancelRequest::has_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(355);
}

const char* OrderCancelRequest::get_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(355).data();
}

void OrderCancelRequest::set_EncodedText(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(355, data, data_length);
}


} // namespace

} // namespace