/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "OrderCancelReject.h"

namespace custom
{

namespace FIX44
{

OrderCancelReject::OrderCancelReject(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

OrderCancelReject::OrderCancelReject(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* OrderCancelReject::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void OrderCancelReject::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void OrderCancelReject::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool OrderCancelReject::has_OrdStatus() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(39);
}

char OrderCancelReject::get_OrdStatus() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(39);
}

void OrderCancelReject::set_OrdStatus(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(39, val);
}

bool OrderCancelReject::has_CxlRejResponseTo() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(434);
}

char OrderCancelReject::get_CxlRejResponseTo() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(434);
}

void OrderCancelReject::set_CxlRejResponseTo(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(434, val);
}

bool OrderCancelReject::has_OrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(37);
}

std::string_view OrderCancelReject::get_OrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(37)->to_string_view();
}

void OrderCancelReject::set_OrderID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(37, buffer);
}

bool OrderCancelReject::has_SecondaryOrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(198);
}

std::string_view OrderCancelReject::get_SecondaryOrderID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(198)->to_string_view();
}

void OrderCancelReject::set_SecondaryOrderID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(198, buffer);
}

bool OrderCancelReject::has_SecondaryClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(526);
}

std::string_view OrderCancelReject::get_SecondaryClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(526)->to_string_view();
}

void OrderCancelReject::set_SecondaryClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(526, buffer);
}

bool OrderCancelReject::has_ClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(11);
}

std::string_view OrderCancelReject::get_ClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(11)->to_string_view();
}

void OrderCancelReject::set_ClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(11, buffer);
}

bool OrderCancelReject::has_ClOrdLinkID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(583);
}

std::string_view OrderCancelReject::get_ClOrdLinkID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(583)->to_string_view();
}

void OrderCancelReject::set_ClOrdLinkID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(583, buffer);
}

bool OrderCancelReject::has_OrigClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(41);
}

std::string_view OrderCancelReject::get_OrigClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(41)->to_string_view();
}

void OrderCancelReject::set_OrigClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(41, buffer);
}

bool OrderCancelReject::has_OrigOrdModTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(586);
}

std::string_view OrderCancelReject::get_OrigOrdModTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(586)->to_string_view();
}

void OrderCancelReject::set_OrigOrdModTime(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(586, buffer);
}

bool OrderCancelReject::has_ListID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(66);
}

std::string_view OrderCancelReject::get_ListID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(66)->to_string_view();
}

void OrderCancelReject::set_ListID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(66, buffer);
}

bool OrderCancelReject::has_Account() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(1);
}

std::string_view OrderCancelReject::get_Account() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(1)->to_string_view();
}

void OrderCancelReject::set_Account(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(1, buffer);
}

bool OrderCancelReject::has_TradeOriginationDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(229);
}

std::string_view OrderCancelReject::get_TradeOriginationDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(229)->to_string_view();
}

void OrderCancelReject::set_TradeOriginationDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(229, buffer);
}

bool OrderCancelReject::has_TradeDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(75);
}

std::string_view OrderCancelReject::get_TradeDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(75)->to_string_view();
}

void OrderCancelReject::set_TradeDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(75, buffer);
}

bool OrderCancelReject::has_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(58);
}

std::string_view OrderCancelReject::get_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(58)->to_string_view();
}

void OrderCancelReject::set_Text(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(58, buffer);
}

bool OrderCancelReject::has_CxlRejReason() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(102);
}

bool OrderCancelReject::has_EncodedTextLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(354);
}

bool OrderCancelReject::has_TransactTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(60);
}

std::string_view OrderCancelReject::get_TransactTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(60)->to_string_view();
}

void OrderCancelReject::set_timestamp_TransactTime()
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_timestamp_tag(60);
}

bool OrderCancelReject::has_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(355);
}

const char* OrderCancelReject::get_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(355).data();
}

void OrderCancelReject::set_EncodedText(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(355, data, data_length);
}


} // namespace

} // namespace