/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "Reject.h"

namespace custom
{

namespace FIX44
{

Reject::Reject(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

Reject::Reject(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* Reject::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void Reject::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void Reject::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool Reject::has_RefMsgType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(372);
}

std::string_view Reject::get_RefMsgType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(372)->to_string_view();
}

void Reject::set_RefMsgType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(372, buffer);
}

bool Reject::has_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(58);
}

std::string_view Reject::get_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(58)->to_string_view();
}

void Reject::set_Text(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(58, buffer);
}

bool Reject::has_RefSeqNum() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(45);
}

bool Reject::has_RefTagID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(371);
}

bool Reject::has_SessionRejectReason() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(373);
}

bool Reject::has_EncodedTextLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(354);
}

bool Reject::has_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(355);
}

const char* Reject::get_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(355).data();
}

void Reject::set_EncodedText(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(355, data, data_length);
}


} // namespace

} // namespace