/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "ResendRequest.h"

namespace custom
{

namespace FIX44
{

ResendRequest::ResendRequest(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

ResendRequest::ResendRequest(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* ResendRequest::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void ResendRequest::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void ResendRequest::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool ResendRequest::has_BeginSeqNo() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(7);
}

bool ResendRequest::has_EndSeqNo() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(16);
}


} // namespace

} // namespace