/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "SequenceReset.h"

namespace custom
{

namespace FIX44
{

SequenceReset::SequenceReset(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

SequenceReset::SequenceReset(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* SequenceReset::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void SequenceReset::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void SequenceReset::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool SequenceReset::has_GapFillFlag() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(123);
}

bool SequenceReset::get_GapFillFlag() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<bool>(123);
}

void SequenceReset::set_GapFillFlag(bool val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(123, val);
}

bool SequenceReset::has_NewSeqNo() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(36);
}


} // namespace

} // namespace