/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cstdint>
#include <cstddef>
#include <string>

#include <llfix/fix_server.h>
#include <llfix/core/utilities/tcp_reactor_scalable.h>

namespace llfix
{
// Forward declarations
class FixString;
class FixSession;
class IncomingFixMessage;
}

namespace custom
{

class MyServer : public llfix::FixServer<llfix::TcpReactorScalable<>>
{
    public:
        // Application-level inbound messages
        void on_new_order(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_cancel_order(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_replace_order(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_application_level_reject(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_session_level_reject(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_custom_message(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;

        // New session attempts
        llfix::FixSession* accept_session(std::size_t peer_index, const llfix::IncomingFixMessage* incoming_fix_message, const char* buffer, std::size_t buffer_length, uint32_t parser_reject_code) override;

        // Session logon/logout requests
        void process_logon_request(llfix::FixSession* session, std::size_t peer_index, const llfix::IncomingFixMessage* message) override;
        bool authenticate_logon_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_logon_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_logout_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        // Session-level client requests
        void on_client_resend_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_client_test_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        void on_client_heartbeat(llfix::FixSession* session) override;

        // Session controls and authentication
        bool process_incoming_throttling(llfix::FixSession* session, const llfix::IncomingFixMessage* incoming_fix_message) override;
        void process_schedule_validator(llfix::FixSession* session) override;

        // Outbound session responses and requests
        bool send_heartbeat(llfix::FixSession* session, llfix::FixString* test_request_id) override;
        bool send_logon_response(llfix::FixSession* session, const llfix::IncomingFixMessage* message) override;
        bool send_logout_message(llfix::FixSession* session, const std::string& reason_text = "") override;
        bool send_test_request(llfix::FixSession* session) override;
        bool send_resend_request(llfix::FixSession* session) override;
        bool send_sequence_reset_message(llfix::FixSession* session, uint32_t desired_sequence_no) override;
        bool send_gap_fill_message(llfix::FixSession* session) override;
        bool send_reject_message(llfix::FixSession* session, const llfix::IncomingFixMessage* incoming_message, uint32_t reject_reason_code, const char* buffer_message, std::size_t buffer_message_length, uint32_t error_tag) override;
        bool send_throttle_reject_message(llfix::FixSession* session, const llfix::IncomingFixMessage* incoming_message) override;
};

} // namespace