/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include <llfix/engine.h>
#include <llfix/fix_string.h>
#include <llfix/incoming_fix_message.h>
#include <llfix/fix_session.h>

#include "MyServer.h"

namespace custom
{

// Called when a new order message is received from a client
void MyServer::on_new_order(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when an order cancel request is received from a client
void MyServer::on_cancel_order(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when an order replace request is received from a client
void MyServer::on_replace_order(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when an application-level reject is received from a client
void MyServer::on_application_level_reject(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when a session-level reject is received from a client
void MyServer::on_session_level_reject(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when a custom or user-defined FIX message is received
void MyServer::on_custom_message(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when a new inbound TCP connection made
llfix::FixSession* MyServer::accept_session(std::size_t peer_index, const llfix::IncomingFixMessage* incoming_fix_message, const char* buffer, std::size_t buffer_length, uint32_t parser_reject_code)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::accept_session(peer_index, incoming_fix_message, buffer, buffer_length, parser_reject_code);
}

// Handles authentication and validation of a logon request
void MyServer::process_logon_request(llfix::FixSession* session, std::size_t peer_index, const llfix::IncomingFixMessage* message)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::process_logon_request(session, peer_index, message);
}

// Handles authentication and validation of a logon request
bool MyServer::authenticate_logon_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::authenticate_logon_request(session, message);
}

// Called when a logon request is received from a client
void MyServer::on_logon_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when a logout request is received from a client
void MyServer::on_logout_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when a resend request is received from a client
void MyServer::on_client_resend_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when a test request is received from a client
void MyServer::on_client_test_request(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
}

// Called when a heartbeat is received from a client
void MyServer::on_client_heartbeat(llfix::FixSession* session)
{
}

// Handles throttling checks for incoming client messages
bool MyServer::process_incoming_throttling(llfix::FixSession* session, const llfix::IncomingFixMessage* incoming_fix_message)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::process_incoming_throttling(session, incoming_fix_message);
}

// Handles scheduler checks
void MyServer::process_schedule_validator(llfix::FixSession* session)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::process_schedule_validator(session);
}

// Handles sending a heartbeat message to the client
bool MyServer::send_heartbeat(llfix::FixSession* session, llfix::FixString* test_request_id)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_heartbeat(session, test_request_id);
}

// Handles sending a logon response to the client
bool MyServer::send_logon_response(llfix::FixSession* session, const llfix::IncomingFixMessage* message)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_logon_response(session, message);
}

// Handles sending a logout message to the client
bool MyServer::send_logout_message(llfix::FixSession* session, const std::string& reason_text)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_logout_message(session, reason_text);
}

// Handles sending a test request to the client
bool MyServer::send_test_request(llfix::FixSession* session)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_test_request(session);
}

// Handles sending a resend request to the client
bool MyServer::send_resend_request(llfix::FixSession* session)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_resend_request(session);
}

// Handles sending a sequence reset message to the client
bool MyServer::send_sequence_reset_message(llfix::FixSession* session, uint32_t desired_sequence_no)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_sequence_reset_message(session, desired_sequence_no);
}

// Handles sending a gap fill sequence reset message
bool MyServer::send_gap_fill_message(llfix::FixSession* session)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_gap_fill_message(session);
}

// Handles sending a reject message to the client
bool MyServer::send_reject_message(llfix::FixSession* session, const llfix::IncomingFixMessage* incoming_message, uint32_t reject_reason_code, const char* buffer_message, std::size_t buffer_message_length, uint32_t error_tag=0)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_reject_message(session, incoming_message, reject_reason_code, buffer_message, buffer_message_length, error_tag);
}

// Handles sending a throttle reject message to the client
bool MyServer::send_throttle_reject_message(llfix::FixSession* session, const llfix::IncomingFixMessage* incoming_message)
{
    return llfix::FixServer<llfix::TcpReactorScalable<>>::send_throttle_reject_message(session, incoming_message);
}

} // namespace