/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

namespace custom
{

namespace FIX44
{

enum class CxlRejReason
{
    TOO_LATE_TO_CANCEL=0,
    UNKNOWN_ORDER=1,
    BROKER_CREDIT=2,
    ORDER_ALREADY_IN_PENDING_STATUS=3,
    UNABLE_TO_PROCESS_ORDER_MASS_CANCEL_REQUEST=4,
    ORIG_ORD_MOD_TIME=5,
    DUPLICATE_CL_ORD_ID=6,
    OTHER=99
};

} // namespace FIX44
} // namespace custom