/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace CxlRejResponseTo
{
    static inline constexpr char ORDER_CANCEL_REQUEST='1';
    static inline constexpr char ORDER_CANCEL='2';
} // namespace CxlRejResponseTo

} // namespace FIX44
} // namespace custom