/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

namespace custom
{

namespace FIX44
{

enum class EncryptMethod
{
    NONE=0,
    PKCS=1,
    DES=2,
    PKCSDES=3,
    PGPDES=4,
    PGPDESMD5=5,
    PEM=6
};

} // namespace FIX44
} // namespace custom