/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <string_view>

namespace custom
{

namespace FIX44
{

namespace ExecInst
{
    static inline constexpr std::string_view NOT_HELD="1";
    static inline constexpr std::string_view WORK="2";
    static inline constexpr std::string_view GO_ALONG="3";
    static inline constexpr std::string_view OVER_THE_DAY="4";
    static inline constexpr std::string_view HELD="5";
    static inline constexpr std::string_view PARTICIPATE_DO_NOT_INITIATE="6";
    static inline constexpr std::string_view STRICT_SCALE="7";
    static inline constexpr std::string_view TRY_TO_SCALE="8";
    static inline constexpr std::string_view STAY_ON_BID_SIDE="9";
    static inline constexpr std::string_view STAY_ON_OFFER_SIDE="0";
    static inline constexpr std::string_view NO_CROSS="A";
    static inline constexpr std::string_view OK_TO_CROSS="B";
    static inline constexpr std::string_view CALL_FIRST="C";
    static inline constexpr std::string_view PERCENT_OF_VOLUME="D";
    static inline constexpr std::string_view DO_NOT_INCREASE="E";
    static inline constexpr std::string_view DO_NOT_REDUCE="F";
    static inline constexpr std::string_view ALL_OR_NONE="G";
    static inline constexpr std::string_view REINSTATE_ON_SYSTEM_FAILURE="H";
    static inline constexpr std::string_view INSTITUTIONS_ONLY="I";
    static inline constexpr std::string_view REINSTATE_ON_TRADING_HALT="J";
    static inline constexpr std::string_view CANCEL_ON_TRADING_HALT="K";
    static inline constexpr std::string_view LAST_PEG="L";
    static inline constexpr std::string_view MID_PRICE_PEG="M";
    static inline constexpr std::string_view NON_NEGOTIABLE="N";
    static inline constexpr std::string_view OPENING_PEG="O";
    static inline constexpr std::string_view MARKET_PEG="P";
    static inline constexpr std::string_view CANCEL_ON_SYSTEM_FAILURE="Q";
    static inline constexpr std::string_view PRIMARY_PEG="R";
    static inline constexpr std::string_view SUSPEND="S";
    static inline constexpr std::string_view CUSTOMER_DISPLAY_INSTRUCTION="U";
    static inline constexpr std::string_view NETTING="V";
    static inline constexpr std::string_view PEG_TO_VWAP="W";
    static inline constexpr std::string_view TRADE_ALONG="X";
    static inline constexpr std::string_view TRY_TO_STOP="Y";
    static inline constexpr std::string_view CANCEL_IF_NOT_BEST="Z";
    static inline constexpr std::string_view TRAILING_STOP_PEG="a";
    static inline constexpr std::string_view STRICT_LIMIT="b";
    static inline constexpr std::string_view IGNORE_PRICE_VALIDITY_CHECKS="c";
    static inline constexpr std::string_view PEG_TO_LIMIT_PRICE="d";
    static inline constexpr std::string_view WORK_TO_TARGET_STRATEGY="e";
} // namespace ExecInst

} // namespace FIX44
} // namespace custom