/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace HandlInst
{
    static inline constexpr char AUTOMATED_EXECUTION_NO_INTERVENTION='1';
    static inline constexpr char AUTOMATED_EXECUTION_INTERVENTION_OK='2';
    static inline constexpr char MANUAL_ORDER='3';
} // namespace HandlInst

} // namespace FIX44
} // namespace custom