/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

namespace custom
{

namespace FIX44
{

enum class LastLiquidityInd
{
    ADDED_LIQUIDITY=1,
    REMOVED_LIQUIDITY=2,
    LIQUIDITY_ROUTED_OUT=3
};

} // namespace FIX44
} // namespace custom