/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <string_view>

namespace custom
{

namespace FIX44
{

namespace MessageEncoding
{
    static inline constexpr std::string_view ISO2022_JP="ISO-2022-JP";
    static inline constexpr std::string_view EUCJP="EUC-JP";
    static inline constexpr std::string_view SHIFT_JIS="Shift_JIS";
    static inline constexpr std::string_view UTF8="UTF-8";
} // namespace MessageEncoding

} // namespace FIX44
} // namespace custom