/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <string_view>

namespace custom
{

namespace FIX44
{

namespace MsgType
{
    static inline constexpr std::string_view HEARTBEAT="0";
    static inline constexpr std::string_view TEST_REQUEST="1";
    static inline constexpr std::string_view RESEND_REQUEST="2";
    static inline constexpr std::string_view REJECT="3";
    static inline constexpr std::string_view SEQUENCE_RESET="4";
    static inline constexpr std::string_view LOGOUT="5";
    static inline constexpr std::string_view IOI="6";
    static inline constexpr std::string_view ADVERTISEMENT="7";
    static inline constexpr std::string_view EXECUTION_REPORT="8";
    static inline constexpr std::string_view ORDER_CANCEL_REJECT="9";
    static inline constexpr std::string_view LOGON="A";
    static inline constexpr std::string_view NEWS="B";
    static inline constexpr std::string_view EMAIL="C";
    static inline constexpr std::string_view NEW_ORDER_SINGLE="D";
    static inline constexpr std::string_view NEW_ORDER_LIST="E";
    static inline constexpr std::string_view ORDER_CANCEL_REQUEST="F";
    static inline constexpr std::string_view ORDER_CANCEL_REPLACE_REQUEST="G";
    static inline constexpr std::string_view ORDER_STATUS_REQUEST="H";
    static inline constexpr std::string_view ALLOCATION_INSTRUCTION="J";
    static inline constexpr std::string_view LIST_CANCEL_REQUEST="K";
    static inline constexpr std::string_view LIST_EXECUTE="L";
    static inline constexpr std::string_view LIST_STATUS_REQUEST="M";
    static inline constexpr std::string_view LIST_STATUS="N";
    static inline constexpr std::string_view ALLOCATION_INSTRUCTION_ACK="P";
    static inline constexpr std::string_view DONT_KNOW_TRADE="Q";
    static inline constexpr std::string_view QUOTE_REQUEST="R";
    static inline constexpr std::string_view QUOTE="S";
    static inline constexpr std::string_view SETTLEMENT_INSTRUCTIONS="T";
    static inline constexpr std::string_view MARKET_DATA_REQUEST="V";
    static inline constexpr std::string_view MARKET_DATA_SNAPSHOT_FULL_REFRESH="W";
    static inline constexpr std::string_view MARKET_DATA_INCREMENTAL_REFRESH="X";
    static inline constexpr std::string_view MARKET_DATA_REQUEST_REJECT="Y";
    static inline constexpr std::string_view QUOTE_CANCEL="Z";
    static inline constexpr std::string_view QUOTE_STATUS_REQUEST="a";
    static inline constexpr std::string_view MASS_QUOTE_ACKNOWLEDGEMENT="b";
    static inline constexpr std::string_view SECURITY_DEFINITION_REQUEST="c";
    static inline constexpr std::string_view SECURITY_DEFINITION="d";
    static inline constexpr std::string_view SECURITY_STATUS_REQUEST="e";
    static inline constexpr std::string_view SECURITY_STATUS="f";
    static inline constexpr std::string_view TRADING_SESSION_STATUS_REQUEST="g";
    static inline constexpr std::string_view TRADING_SESSION_STATUS="h";
    static inline constexpr std::string_view MASS_QUOTE="i";
    static inline constexpr std::string_view BUSINESS_MESSAGE_REJECT="j";
    static inline constexpr std::string_view BID_REQUEST="k";
    static inline constexpr std::string_view BID_RESPONSE="l";
    static inline constexpr std::string_view LIST_STRIKE_PRICE="m";
    static inline constexpr std::string_view XML_NON_FIX="n";
    static inline constexpr std::string_view REGISTRATION_INSTRUCTIONS="o";
    static inline constexpr std::string_view REGISTRATION_INSTRUCTIONS_RESPONSE="p";
    static inline constexpr std::string_view ORDER_MASS_CANCEL_REQUEST="q";
    static inline constexpr std::string_view ORDER_MASS_CANCEL_REPORT="r";
    static inline constexpr std::string_view NEW_ORDER_CROSS="s";
    static inline constexpr std::string_view CROSS_ORDER_CANCEL_REPLACE_REQUEST="t";
    static inline constexpr std::string_view CROSS_ORDER_CANCEL_REQUEST="u";
    static inline constexpr std::string_view SECURITY_TYPE_REQUEST="v";
    static inline constexpr std::string_view SECURITY_TYPES="w";
    static inline constexpr std::string_view SECURITY_LIST_REQUEST="x";
    static inline constexpr std::string_view SECURITY_LIST="y";
    static inline constexpr std::string_view DERIVATIVE_SECURITY_LIST_REQUEST="z";
    static inline constexpr std::string_view DERIVATIVE_SECURITY_LIST="AA";
    static inline constexpr std::string_view NEW_ORDER_MULTILEG="AB";
    static inline constexpr std::string_view MULTILEG_ORDER_CANCEL_REPLACE="AC";
    static inline constexpr std::string_view TRADE_CAPTURE_REPORT_REQUEST="AD";
    static inline constexpr std::string_view TRADE_CAPTURE_REPORT="AE";
    static inline constexpr std::string_view ORDER_MASS_STATUS_REQUEST="AF";
    static inline constexpr std::string_view QUOTE_REQUEST_REJECT="AG";
    static inline constexpr std::string_view RFQ_REQUEST="AH";
    static inline constexpr std::string_view QUOTE_STATUS_REPORT="AI";
    static inline constexpr std::string_view QUOTE_RESPONSE="AJ";
    static inline constexpr std::string_view CONFIRMATION="AK";
    static inline constexpr std::string_view POSITION_MAINTENANCE_REQUEST="AL";
    static inline constexpr std::string_view POSITION_MAINTENANCE_REPORT="AM";
    static inline constexpr std::string_view REQUEST_FOR_POSITIONS="AN";
    static inline constexpr std::string_view REQUEST_FOR_POSITIONS_ACK="AO";
    static inline constexpr std::string_view POSITION_REPORT="AP";
    static inline constexpr std::string_view TRADE_CAPTURE_REPORT_REQUEST_ACK="AQ";
    static inline constexpr std::string_view TRADE_CAPTURE_REPORT_ACK="AR";
    static inline constexpr std::string_view ALLOCATION_REPORT="AS";
    static inline constexpr std::string_view ALLOCATION_REPORT_ACK="AT";
    static inline constexpr std::string_view CONFIRMATION_ACK="AU";
    static inline constexpr std::string_view SETTLEMENT_INSTRUCTION_REQUEST="AV";
    static inline constexpr std::string_view ASSIGNMENT_REPORT="AW";
    static inline constexpr std::string_view COLLATERAL_REQUEST="AX";
    static inline constexpr std::string_view COLLATERAL_ASSIGNMENT="AY";
    static inline constexpr std::string_view COLLATERAL_RESPONSE="AZ";
    static inline constexpr std::string_view COLLATERAL_REPORT="BA";
    static inline constexpr std::string_view COLLATERAL_INQUIRY="BB";
    static inline constexpr std::string_view NETWORK_COUNTERPARTY_SYSTEM_STATUS_REQUEST="BC";
    static inline constexpr std::string_view NETWORK_COUNTERPARTY_SYSTEM_STATUS_RESPONSE="BD";
    static inline constexpr std::string_view USER_REQUEST="BE";
    static inline constexpr std::string_view USER_RESPONSE="BF";
    static inline constexpr std::string_view COLLATERAL_INQUIRY_ACK="BG";
    static inline constexpr std::string_view CONFIRMATION_REQUEST="BH";
} // namespace MsgType

} // namespace FIX44
} // namespace custom