/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace OrdStatus
{
    static inline constexpr char NEW='0';
    static inline constexpr char PARTIALLY_FILLED='1';
    static inline constexpr char FILLED='2';
    static inline constexpr char DONE_FOR_DAY='3';
    static inline constexpr char CANCELED='4';
    static inline constexpr char PENDING_CANCEL='6';
    static inline constexpr char STOPPED='7';
    static inline constexpr char REJECTED='8';
    static inline constexpr char SUSPENDED='9';
    static inline constexpr char PENDING_NEW='A';
    static inline constexpr char CALCULATED='B';
    static inline constexpr char EXPIRED='C';
    static inline constexpr char ACCEPTED_FOR_BIDDING='D';
    static inline constexpr char PENDING_REPLACE='E';
} // namespace OrdStatus

} // namespace FIX44
} // namespace custom