/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once



namespace custom
{

namespace FIX44
{

namespace PartyIDSource
{
    static inline constexpr char BIC='B';
    static inline constexpr char GENERAL_IDENTIFIER='C';
    static inline constexpr char PROPRIETARY='D';
    static inline constexpr char ISO_COUNTRY_CODE='E';
    static inline constexpr char SETTLEMENT_ENTITY_LOCATION='F';
    static inline constexpr char MIC='G';
    static inline constexpr char CSD_PARTICIPANT='H';
    static inline constexpr char KOREAN_INVESTOR_ID='1';
    static inline constexpr char TAIWANESE_FOREIGN_INVESTOR_ID='2';
    static inline constexpr char TAIWANESE_TRADING_ACCT='3';
    static inline constexpr char MALAYSIAN_CENTRAL_DEPOSITORY='4';
    static inline constexpr char CHINESE_INVESTOR_ID='5';
    static inline constexpr char UK_NATIONAL_INSURANCE_OR_PENSION_NUMBER='6';
    static inline constexpr char US_SOCIAL_SECURITY_NUMBER='7';
    static inline constexpr char US_EMPLOYER_OR_TAX_ID_NUMBER='8';
    static inline constexpr char AUSTRALIAN_BUSINESS_NUMBER='9';
    static inline constexpr char AUSTRALIAN_TAX_FILE_NUMBER='A';
    static inline constexpr char ISITC_ACRONYM='I';
} // namespace PartyIDSource

} // namespace FIX44
} // namespace custom