/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

namespace custom
{

namespace FIX44
{

enum class PriceType
{
    PERCENTAGE=1,
    PER_UNIT=2,
    FIXED_AMOUNT=3,
    DISCOUNT=4,
    PREMIUM=5,
    SPREAD=6,
    TED_PRICE=7,
    TED_YIELD=8,
    YIELD=9,
    FIXED_CABINET_TRADE_PRICE=10,
    VARIABLE_CABINET_TRADE_PRICE=11
};

} // namespace FIX44
} // namespace custom