/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <string_view>

namespace custom
{

namespace FIX44
{

namespace SecurityIDSource
{
    static inline constexpr std::string_view CUSIP="1";
    static inline constexpr std::string_view SEDOL="2";
    static inline constexpr std::string_view QUIK="3";
    static inline constexpr std::string_view ISIN_NUMBER="4";
    static inline constexpr std::string_view RIC_CODE="5";
    static inline constexpr std::string_view ISO_CURRENCY_CODE="6";
    static inline constexpr std::string_view ISO_COUNTRY_CODE="7";
    static inline constexpr std::string_view EXCHANGE_SYMBOL="8";
    static inline constexpr std::string_view CONSOLIDATED_TAPE_ASSOCIATION="9";
    static inline constexpr std::string_view BLOOMBERG_SYMBOL="A";
    static inline constexpr std::string_view WERTPAPIER="B";
    static inline constexpr std::string_view DUTCH="C";
    static inline constexpr std::string_view VALOREN="D";
    static inline constexpr std::string_view SICOVAM="E";
    static inline constexpr std::string_view BELGIAN="F";
    static inline constexpr std::string_view COMMON="G";
    static inline constexpr std::string_view CLEARING_HOUSE="H";
    static inline constexpr std::string_view ISDA_FP_ML_SPECIFICATION="I";
    static inline constexpr std::string_view OPTION_PRICE_REPORTING_AUTHORITY="J";
} // namespace SecurityIDSource

} // namespace FIX44
} // namespace custom