/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <string_view>

namespace custom
{

namespace FIX44
{

namespace SecurityType
{
    static inline constexpr std::string_view EURO_SUPRANATIONAL_COUPONS="EUSUPRA";
    static inline constexpr std::string_view FEDERAL_AGENCY_COUPON="FAC";
    static inline constexpr std::string_view FEDERAL_AGENCY_DISCOUNT_NOTE="FADN";
    static inline constexpr std::string_view PRIVATE_EXPORT_FUNDING="PEF";
    static inline constexpr std::string_view USD_SUPRANATIONAL_COUPONS="SUPRA";
    static inline constexpr std::string_view CORPORATE_BOND="CORP";
    static inline constexpr std::string_view CORPORATE_PRIVATE_PLACEMENT="CPP";
    static inline constexpr std::string_view CONVERTIBLE_BOND="CB";
    static inline constexpr std::string_view DUAL_CURRENCY="DUAL";
    static inline constexpr std::string_view EURO_CORPORATE_BOND="EUCORP";
    static inline constexpr std::string_view INDEXED_LINKED="XLINKD";
    static inline constexpr std::string_view STRUCTURED_NOTES="STRUCT";
    static inline constexpr std::string_view YANKEE_CORPORATE_BOND="YANK";
    static inline constexpr std::string_view FOREIGN_EXCHANGE_CONTRACT="FOR";
    static inline constexpr std::string_view COMMON_STOCK="CS";
    static inline constexpr std::string_view PREFERRED_STOCK="PS";
    static inline constexpr std::string_view BRADY_BOND="BRADY";
    static inline constexpr std::string_view EURO_SOVEREIGNS="EUSOV";
    static inline constexpr std::string_view US_TREASURY_BOND="TBOND";
    static inline constexpr std::string_view INTEREST_STRIP_FROM_ANY_BOND_OR_NOTE="TINT";
    static inline constexpr std::string_view TREASURY_INFLATION_PROTECTED_SECURITIES="TIPS";
    static inline constexpr std::string_view PRINCIPAL_STRIP_OF_A_CALLABLE_BOND_OR_NOTE="TCAL";
    static inline constexpr std::string_view PRINCIPAL_STRIP_FROM_A_NON_CALLABLE_BOND_OR_NOTE="TPRN";
    static inline constexpr std::string_view US_TREASURY_NOTE_OLD="UST";
    static inline constexpr std::string_view US_TREASURY_BILL_OLD="USTB";
    static inline constexpr std::string_view US_TREASURY_NOTE="TNOTE";
    static inline constexpr std::string_view US_TREASURY_BILL="TBILL";
    static inline constexpr std::string_view REPURCHASE="REPO";
    static inline constexpr std::string_view FORWARD="FORWARD";
    static inline constexpr std::string_view BUY_SELLBACK="BUYSELL";
    static inline constexpr std::string_view SECURITIES_LOAN="SECLOAN";
    static inline constexpr std::string_view SECURITIES_PLEDGE="SECPLEDGE";
    static inline constexpr std::string_view TERM_LOAN="TERM";
    static inline constexpr std::string_view REVOLVER_LOAN="RVLV";
    static inline constexpr std::string_view REVOLVER="RVLVTRM";
    static inline constexpr std::string_view BRIDGE_LOAN="BRIDGE";
    static inline constexpr std::string_view LETTER_OF_CREDIT="LOFC";
    static inline constexpr std::string_view SWING_LINE_FACILITY="SWING";
    static inline constexpr std::string_view DEBTOR_IN_POSSESSION="DINP";
    static inline constexpr std::string_view DEFAULTED="DEFLTED";
    static inline constexpr std::string_view WITHDRAWN="WITHDRN";
    static inline constexpr std::string_view REPLACED="REPLACD";
    static inline constexpr std::string_view MATURED="MATURED";
    static inline constexpr std::string_view AMENDED="AMENDED";
    static inline constexpr std::string_view RETIRED="RETIRED";
    static inline constexpr std::string_view BANKERS_ACCEPTANCE="BA";
    static inline constexpr std::string_view BANK_NOTES="BN";
    static inline constexpr std::string_view BILL_OF_EXCHANGES="BOX";
    static inline constexpr std::string_view CERTIFICATE_OF_DEPOSIT="CD";
    static inline constexpr std::string_view CALL_LOANS="CL";
    static inline constexpr std::string_view COMMERCIAL_PAPER="CP";
    static inline constexpr std::string_view DEPOSIT_NOTES="DN";
    static inline constexpr std::string_view EURO_CERTIFICATE_OF_DEPOSIT="EUCD";
    static inline constexpr std::string_view EURO_COMMERCIAL_PAPER="EUCP";
    static inline constexpr std::string_view LIQUIDITY_NOTE="LQN";
    static inline constexpr std::string_view MEDIUM_TERM_NOTES="MTN";
    static inline constexpr std::string_view OVERNIGHT="ONITE";
    static inline constexpr std::string_view PROMISSORY_NOTE="PN";
    static inline constexpr std::string_view PLAZOS_FIJOS="PZFJ";
    static inline constexpr std::string_view SHORT_TERM_LOAN_NOTE="STN";
    static inline constexpr std::string_view TIME_DEPOSIT="TD";
    static inline constexpr std::string_view EXTENDED_COMM_NOTE="XCN";
    static inline constexpr std::string_view YANKEE_CERTIFICATE_OF_DEPOSIT="YCD";
    static inline constexpr std::string_view ASSET_BACKED_SECURITIES="ABS";
    static inline constexpr std::string_view CORP="CMBS";
    static inline constexpr std::string_view COLLATERALIZED_MORTGAGE_OBLIGATION="CMO";
    static inline constexpr std::string_view IOETTE_MORTGAGE="IET";
    static inline constexpr std::string_view MORTGAGE_BACKED_SECURITIES="MBS";
    static inline constexpr std::string_view MORTGAGE_INTEREST_ONLY="MIO";
    static inline constexpr std::string_view MORTGAGE_PRINCIPAL_ONLY="MPO";
    static inline constexpr std::string_view MORTGAGE_PRIVATE_PLACEMENT="MPP";
    static inline constexpr std::string_view MISCELLANEOUS_PASS_THROUGH="MPT";
    static inline constexpr std::string_view PFANDBRIEFE="PFAND";
    static inline constexpr std::string_view TO_BE_ANNOUNCED="TBA";
    static inline constexpr std::string_view OTHER_ANTICIPATION_NOTES="AN";
    static inline constexpr std::string_view CERTIFICATE_OF_OBLIGATION="COFO";
    static inline constexpr std::string_view CERTIFICATE_OF_PARTICIPATION="COFP";
    static inline constexpr std::string_view GENERAL_OBLIGATION_BONDS="GO";
    static inline constexpr std::string_view MANDATORY_TENDER="MT";
    static inline constexpr std::string_view REVENUE_ANTICIPATION_NOTE="RAN";
    static inline constexpr std::string_view REVENUE_BONDS="REV";
    static inline constexpr std::string_view SPECIAL_ASSESSMENT="SPCLA";
    static inline constexpr std::string_view SPECIAL_OBLIGATION="SPCLO";
    static inline constexpr std::string_view SPECIAL_TAX="SPCLT";
    static inline constexpr std::string_view TAX_ANTICIPATION_NOTE="TAN";
    static inline constexpr std::string_view TAX_ALLOCATION="TAXA";
    static inline constexpr std::string_view TAX_EXEMPT_COMMERCIAL_PAPER="TECP";
    static inline constexpr std::string_view TAX_REVENUE_ANTICIPATION_NOTE="TRAN";
    static inline constexpr std::string_view VARIABLE_RATE_DEMAND_NOTE="VRDN";
    static inline constexpr std::string_view WARRANT="WAR";
    static inline constexpr std::string_view MUTUAL_FUND="MF";
    static inline constexpr std::string_view MULTILEG_INSTRUMENT="MLEG";
    static inline constexpr std::string_view NO_SECURITY_TYPE="NONE";
    static inline constexpr std::string_view FUTURE="FUT";
    static inline constexpr std::string_view OPTION="OPT";
} // namespace SecurityType

} // namespace FIX44
} // namespace custom