/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "BusinessMessageReject.h"

namespace custom
{

namespace FIX44
{

BusinessMessageReject::BusinessMessageReject(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

BusinessMessageReject::BusinessMessageReject(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* BusinessMessageReject::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void BusinessMessageReject::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void BusinessMessageReject::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool BusinessMessageReject::has_RefMsgType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(372);
}

std::string_view BusinessMessageReject::get_RefMsgType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(372)->to_string_view();
}

void BusinessMessageReject::set_RefMsgType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(372, buffer);
}

bool BusinessMessageReject::has_BusinessRejectRefID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(379);
}

std::string_view BusinessMessageReject::get_BusinessRejectRefID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(379)->to_string_view();
}

void BusinessMessageReject::set_BusinessRejectRefID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(379, buffer);
}

bool BusinessMessageReject::has_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(58);
}

std::string_view BusinessMessageReject::get_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(58)->to_string_view();
}

void BusinessMessageReject::set_Text(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(58, buffer);
}

bool BusinessMessageReject::has_RefSeqNum() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(45);
}

bool BusinessMessageReject::has_BusinessRejectReason() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(380);
}

bool BusinessMessageReject::has_EncodedTextLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(354);
}

bool BusinessMessageReject::has_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(355);
}

const char* BusinessMessageReject::get_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(355).data();
}

void BusinessMessageReject::set_EncodedText(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(355, data, data_length);
}


} // namespace

} // namespace