/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "Heartbeat.h"

namespace custom
{

namespace FIX44
{

Heartbeat::Heartbeat(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

Heartbeat::Heartbeat(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* Heartbeat::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void Heartbeat::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void Heartbeat::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool Heartbeat::has_TestReqID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(112);
}

std::string_view Heartbeat::get_TestReqID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(112)->to_string_view();
}

void Heartbeat::set_TestReqID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(112, buffer);
}


} // namespace

} // namespace