/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cassert>
#include <cstdint>
#include <cstddef>
#include <string_view>

#include <llfix/incoming_fix_message.h>
#include <llfix/outgoing_fix_message.h>

namespace custom
{

namespace FIX44
{

class Logout
{
    public:
        explicit Logout(llfix::OutgoingFixMessage*);
        explicit Logout(const llfix::IncomingFixMessage*);

        llfix::OutgoingFixMessage* outgoing_message();

        void set_msg_type(char);
        void set_msg_type(const std::string_view&);

        // Text
        bool has_Text() const;
        std::string_view get_Text() const;
        void set_Text(const std::string_view&);
        // EncodedTextLen
        bool has_EncodedTextLen() const;

        template <typename T>
        T get_EncodedTextLen_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(354);
        }

        template <typename T>
        void set_EncodedTextLen(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(354, val);
        }

        // EncodedText
        bool has_EncodedText() const;
        const char* get_EncodedText() const;
        void set_EncodedText(const char*, std::size_t);
    private:
        llfix::OutgoingFixMessage* m_outgoing_message_instance = nullptr;
        const llfix::IncomingFixMessage* m_incoming_message_instance = nullptr;
};

} // namespace

} // namespace