/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "Logout.h"

namespace custom
{

namespace FIX44
{

Logout::Logout(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

Logout::Logout(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* Logout::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void Logout::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void Logout::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool Logout::has_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(58);
}

std::string_view Logout::get_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(58)->to_string_view();
}

void Logout::set_Text(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(58, buffer);
}

bool Logout::has_EncodedTextLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(354);
}

bool Logout::has_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(355);
}

const char* Logout::get_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(355).data();
}

void Logout::set_EncodedText(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(355, data, data_length);
}


} // namespace

} // namespace