/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "Logon.h"

namespace custom
{

namespace FIX44
{

Logon::Logon(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

Logon::Logon(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* Logon::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void Logon::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void Logon::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool Logon::has_ResetSeqNumFlag() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(141);
}

bool Logon::get_ResetSeqNumFlag() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<bool>(141);
}

void Logon::set_ResetSeqNumFlag(bool val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(141, val);
}

bool Logon::has_Username() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(553);
}

std::string_view Logon::get_Username() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(553)->to_string_view();
}

void Logon::set_Username(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(553, buffer);
}

bool Logon::has_Password() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(554);
}

std::string_view Logon::get_Password() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(554)->to_string_view();
}

void Logon::set_Password(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(554, buffer);
}

bool Logon::has_EncryptMethod() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(98);
}

bool Logon::has_HeartBtInt() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(108);
}

bool Logon::has_NextExpectedMsgSeqNum() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(789);
}

bool Logon::has_MaxMessageSize() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(383);
}


} // namespace

} // namespace