/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#include "NewOrderSingle.h"

namespace custom
{

namespace FIX44
{

NewOrderSingle::NewOrderSingle(llfix::OutgoingFixMessage* message)
{
    assert(message);
    m_outgoing_message_instance = message;
}

NewOrderSingle::NewOrderSingle(const llfix::IncomingFixMessage* message)
{
    assert(message);
    m_incoming_message_instance = message;
}

llfix::OutgoingFixMessage* NewOrderSingle::outgoing_message()
{
    assert(m_outgoing_message_instance);
    return m_outgoing_message_instance;
}

void NewOrderSingle::set_msg_type(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

void NewOrderSingle::set_msg_type(const std::string_view& val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_msg_type(val);
}

bool NewOrderSingle::has_HandlInst() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(21);
}

char NewOrderSingle::get_HandlInst() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(21);
}

void NewOrderSingle::set_HandlInst(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(21, val);
}

bool NewOrderSingle::has_Side() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(54);
}

char NewOrderSingle::get_Side() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(54);
}

void NewOrderSingle::set_Side(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(54, val);
}

bool NewOrderSingle::has_OrdType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(40);
}

char NewOrderSingle::get_OrdType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(40);
}

void NewOrderSingle::set_OrdType(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(40, val);
}

bool NewOrderSingle::has_TimeInForce() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(59);
}

char NewOrderSingle::get_TimeInForce() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(59);
}

void NewOrderSingle::set_TimeInForce(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(59, val);
}

bool NewOrderSingle::has_OrderCapacity() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(528);
}

char NewOrderSingle::get_OrderCapacity() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(528);
}

void NewOrderSingle::set_OrderCapacity(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(528, val);
}

bool NewOrderSingle::has_PartyIDSource() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(447);
}

char NewOrderSingle::get_PartyIDSource() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(447);
}

void NewOrderSingle::set_PartyIDSource(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(447, val);
}

bool NewOrderSingle::has_OptAttribute() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(206);
}

char NewOrderSingle::get_OptAttribute() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<char>(206);
}

void NewOrderSingle::set_OptAttribute(char val)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(206, val);
}

bool NewOrderSingle::has_ClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(11);
}

std::string_view NewOrderSingle::get_ClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(11)->to_string_view();
}

void NewOrderSingle::set_ClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(11, buffer);
}

bool NewOrderSingle::has_SecondaryClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(526);
}

std::string_view NewOrderSingle::get_SecondaryClOrdID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(526)->to_string_view();
}

void NewOrderSingle::set_SecondaryClOrdID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(526, buffer);
}

bool NewOrderSingle::has_Account() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(1);
}

std::string_view NewOrderSingle::get_Account() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(1)->to_string_view();
}

void NewOrderSingle::set_Account(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(1, buffer);
}

bool NewOrderSingle::has_ExecInst() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(18);
}

std::string_view NewOrderSingle::get_ExecInst() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(18)->to_string_view();
}

void NewOrderSingle::set_ExecInst(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(18, buffer);
}

bool NewOrderSingle::has_ExDestination() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(100);
}

std::string_view NewOrderSingle::get_ExDestination() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(100)->to_string_view();
}

void NewOrderSingle::set_ExDestination(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(100, buffer);
}

bool NewOrderSingle::has_Currency() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(15);
}

std::string_view NewOrderSingle::get_Currency() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(15)->to_string_view();
}

void NewOrderSingle::set_Currency(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(15, buffer);
}

bool NewOrderSingle::has_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(58);
}

std::string_view NewOrderSingle::get_Text() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(58)->to_string_view();
}

void NewOrderSingle::set_Text(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(58, buffer);
}

bool NewOrderSingle::has_PartyID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(448);
}

std::string_view NewOrderSingle::get_PartyID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(448)->to_string_view();
}

void NewOrderSingle::set_PartyID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(448, buffer);
}

bool NewOrderSingle::has_Symbol() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(55);
}

std::string_view NewOrderSingle::get_Symbol() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(55)->to_string_view();
}

void NewOrderSingle::set_Symbol(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(55, buffer);
}

bool NewOrderSingle::has_SymbolSfx() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(65);
}

std::string_view NewOrderSingle::get_SymbolSfx() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(65)->to_string_view();
}

void NewOrderSingle::set_SymbolSfx(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(65, buffer);
}

bool NewOrderSingle::has_SecurityID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(48);
}

std::string_view NewOrderSingle::get_SecurityID() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(48)->to_string_view();
}

void NewOrderSingle::set_SecurityID(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(48, buffer);
}

bool NewOrderSingle::has_SecurityIDSource() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(22);
}

std::string_view NewOrderSingle::get_SecurityIDSource() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(22)->to_string_view();
}

void NewOrderSingle::set_SecurityIDSource(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(22, buffer);
}

bool NewOrderSingle::has_CFICode() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(461);
}

std::string_view NewOrderSingle::get_CFICode() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(461)->to_string_view();
}

void NewOrderSingle::set_CFICode(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(461, buffer);
}

bool NewOrderSingle::has_SecurityType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(167);
}

std::string_view NewOrderSingle::get_SecurityType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(167)->to_string_view();
}

void NewOrderSingle::set_SecurityType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(167, buffer);
}

bool NewOrderSingle::has_SecuritySubType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(762);
}

std::string_view NewOrderSingle::get_SecuritySubType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(762)->to_string_view();
}

void NewOrderSingle::set_SecuritySubType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(762, buffer);
}

bool NewOrderSingle::has_MaturityMonthYear() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(200);
}

std::string_view NewOrderSingle::get_MaturityMonthYear() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(200)->to_string_view();
}

void NewOrderSingle::set_MaturityMonthYear(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(200, buffer);
}

bool NewOrderSingle::has_MaturityDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(541);
}

std::string_view NewOrderSingle::get_MaturityDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(541)->to_string_view();
}

void NewOrderSingle::set_MaturityDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(541, buffer);
}

bool NewOrderSingle::has_CouponPaymentDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(224);
}

std::string_view NewOrderSingle::get_CouponPaymentDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(224)->to_string_view();
}

void NewOrderSingle::set_CouponPaymentDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(224, buffer);
}

bool NewOrderSingle::has_IssueDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(225);
}

std::string_view NewOrderSingle::get_IssueDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(225)->to_string_view();
}

void NewOrderSingle::set_IssueDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(225, buffer);
}

bool NewOrderSingle::has_RepoCollateralSecurityType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(239);
}

std::string_view NewOrderSingle::get_RepoCollateralSecurityType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(239)->to_string_view();
}

void NewOrderSingle::set_RepoCollateralSecurityType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(239, buffer);
}

bool NewOrderSingle::has_CreditRating() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(255);
}

std::string_view NewOrderSingle::get_CreditRating() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(255)->to_string_view();
}

void NewOrderSingle::set_CreditRating(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(255, buffer);
}

bool NewOrderSingle::has_InstrRegistry() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(543);
}

std::string_view NewOrderSingle::get_InstrRegistry() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(543)->to_string_view();
}

void NewOrderSingle::set_InstrRegistry(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(543, buffer);
}

bool NewOrderSingle::has_CountryOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(470);
}

std::string_view NewOrderSingle::get_CountryOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(470)->to_string_view();
}

void NewOrderSingle::set_CountryOfIssue(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(470, buffer);
}

bool NewOrderSingle::has_StateOrProvinceOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(471);
}

std::string_view NewOrderSingle::get_StateOrProvinceOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(471)->to_string_view();
}

void NewOrderSingle::set_StateOrProvinceOfIssue(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(471, buffer);
}

bool NewOrderSingle::has_LocaleOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(472);
}

std::string_view NewOrderSingle::get_LocaleOfIssue() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(472)->to_string_view();
}

void NewOrderSingle::set_LocaleOfIssue(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(472, buffer);
}

bool NewOrderSingle::has_RedemptionDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(240);
}

std::string_view NewOrderSingle::get_RedemptionDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(240)->to_string_view();
}

void NewOrderSingle::set_RedemptionDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(240, buffer);
}

bool NewOrderSingle::has_StrikeCurrency() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(947);
}

std::string_view NewOrderSingle::get_StrikeCurrency() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(947)->to_string_view();
}

void NewOrderSingle::set_StrikeCurrency(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(947, buffer);
}

bool NewOrderSingle::has_SecurityExchange() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(207);
}

std::string_view NewOrderSingle::get_SecurityExchange() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(207)->to_string_view();
}

void NewOrderSingle::set_SecurityExchange(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(207, buffer);
}

bool NewOrderSingle::has_Issuer() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(106);
}

std::string_view NewOrderSingle::get_Issuer() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(106)->to_string_view();
}

void NewOrderSingle::set_Issuer(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(106, buffer);
}

bool NewOrderSingle::has_SecurityDesc() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(107);
}

std::string_view NewOrderSingle::get_SecurityDesc() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(107)->to_string_view();
}

void NewOrderSingle::set_SecurityDesc(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(107, buffer);
}

bool NewOrderSingle::has_Pool() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(691);
}

std::string_view NewOrderSingle::get_Pool() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(691)->to_string_view();
}

void NewOrderSingle::set_Pool(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(691, buffer);
}

bool NewOrderSingle::has_ContractSettlMonth() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(667);
}

std::string_view NewOrderSingle::get_ContractSettlMonth() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(667)->to_string_view();
}

void NewOrderSingle::set_ContractSettlMonth(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(667, buffer);
}

bool NewOrderSingle::has_CPRegType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(876);
}

std::string_view NewOrderSingle::get_CPRegType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(876)->to_string_view();
}

void NewOrderSingle::set_CPRegType(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(876, buffer);
}

bool NewOrderSingle::has_DatedDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(873);
}

std::string_view NewOrderSingle::get_DatedDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(873)->to_string_view();
}

void NewOrderSingle::set_DatedDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(873, buffer);
}

bool NewOrderSingle::has_InterestAccrualDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(874);
}

std::string_view NewOrderSingle::get_InterestAccrualDate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(874)->to_string_view();
}

void NewOrderSingle::set_InterestAccrualDate(const std::string_view& buffer)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_tag(874, buffer);
}

bool NewOrderSingle::has_MinQty() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(110);
}

bool NewOrderSingle::has_MaxFloor() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(111);
}

bool NewOrderSingle::has_Price() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(44);
}

bool NewOrderSingle::has_StopPx() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(99);
}

bool NewOrderSingle::has_RepurchaseRate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(227);
}

bool NewOrderSingle::has_Factor() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(228);
}

bool NewOrderSingle::has_StrikePrice() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(202);
}

bool NewOrderSingle::has_ContractMultiplier() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(231);
}

bool NewOrderSingle::has_CouponRate() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(223);
}

bool NewOrderSingle::has_OrderQty() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(38);
}

bool NewOrderSingle::has_CashOrderQty() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(152);
}

bool NewOrderSingle::has_OrderPercent() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(516);
}

bool NewOrderSingle::has_RoundingModulus() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(469);
}

bool NewOrderSingle::has_PriceType() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(423);
}

bool NewOrderSingle::has_EncodedTextLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(354);
}

bool NewOrderSingle::has_NoPartyIDs() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(453);
}

bool NewOrderSingle::has_PartyRole() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(452);
}

bool NewOrderSingle::has_RepurchaseTerm() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(226);
}

bool NewOrderSingle::has_EncodedIssuerLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(348);
}

bool NewOrderSingle::has_EncodedSecurityDescLen() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(350);
}

bool NewOrderSingle::has_TransactTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(60);
}

std::string_view NewOrderSingle::get_TransactTime() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value(60)->to_string_view();
}

void NewOrderSingle::set_timestamp_TransactTime()
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_timestamp_tag(60);
}

bool NewOrderSingle::has_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(355);
}

const char* NewOrderSingle::get_EncodedText() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(355).data();
}

void NewOrderSingle::set_EncodedText(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(355, data, data_length);
}

bool NewOrderSingle::has_EncodedIssuer() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(349);
}

const char* NewOrderSingle::get_EncodedIssuer() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(349).data();
}

void NewOrderSingle::set_EncodedIssuer(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(349, data, data_length);
}

bool NewOrderSingle::has_EncodedSecurityDesc() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->has_tag(351);
}

const char* NewOrderSingle::get_EncodedSecurityDesc() const
{
    assert(m_incoming_message_instance);
    return m_incoming_message_instance->get_tag_value_as<std::string_view>(351).data();
}

void NewOrderSingle::set_EncodedSecurityDesc(const char* data, std::size_t data_length)
{
    assert(m_outgoing_message_instance);
    m_outgoing_message_instance->set_binary_tag(351, data, data_length);
}


} // namespace

} // namespace