/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cassert>
#include <cstdint>
#include <cstddef>
#include <string_view>

#include <llfix/incoming_fix_message.h>
#include <llfix/outgoing_fix_message.h>

namespace custom
{

namespace FIX44
{

class OrderCancelReject
{
    public:
        explicit OrderCancelReject(llfix::OutgoingFixMessage*);
        explicit OrderCancelReject(const llfix::IncomingFixMessage*);

        llfix::OutgoingFixMessage* outgoing_message();

        void set_msg_type(char);
        void set_msg_type(const std::string_view&);

        // OrdStatus
        bool has_OrdStatus() const;
        char get_OrdStatus() const;
        void set_OrdStatus(char);
        // CxlRejResponseTo
        bool has_CxlRejResponseTo() const;
        char get_CxlRejResponseTo() const;
        void set_CxlRejResponseTo(char);
        // OrderID
        bool has_OrderID() const;
        std::string_view get_OrderID() const;
        void set_OrderID(const std::string_view&);
        // SecondaryOrderID
        bool has_SecondaryOrderID() const;
        std::string_view get_SecondaryOrderID() const;
        void set_SecondaryOrderID(const std::string_view&);
        // SecondaryClOrdID
        bool has_SecondaryClOrdID() const;
        std::string_view get_SecondaryClOrdID() const;
        void set_SecondaryClOrdID(const std::string_view&);
        // ClOrdID
        bool has_ClOrdID() const;
        std::string_view get_ClOrdID() const;
        void set_ClOrdID(const std::string_view&);
        // ClOrdLinkID
        bool has_ClOrdLinkID() const;
        std::string_view get_ClOrdLinkID() const;
        void set_ClOrdLinkID(const std::string_view&);
        // OrigClOrdID
        bool has_OrigClOrdID() const;
        std::string_view get_OrigClOrdID() const;
        void set_OrigClOrdID(const std::string_view&);
        // OrigOrdModTime
        bool has_OrigOrdModTime() const;
        std::string_view get_OrigOrdModTime() const;
        void set_OrigOrdModTime(const std::string_view&);
        // ListID
        bool has_ListID() const;
        std::string_view get_ListID() const;
        void set_ListID(const std::string_view&);
        // Account
        bool has_Account() const;
        std::string_view get_Account() const;
        void set_Account(const std::string_view&);
        // TradeOriginationDate
        bool has_TradeOriginationDate() const;
        std::string_view get_TradeOriginationDate() const;
        void set_TradeOriginationDate(const std::string_view&);
        // TradeDate
        bool has_TradeDate() const;
        std::string_view get_TradeDate() const;
        void set_TradeDate(const std::string_view&);
        // Text
        bool has_Text() const;
        std::string_view get_Text() const;
        void set_Text(const std::string_view&);
        // CxlRejReason
        bool has_CxlRejReason() const;

        template <typename T>
        T get_CxlRejReason_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(102);
        }

        template <typename T>
        void set_CxlRejReason(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(102, val);
        }

        // EncodedTextLen
        bool has_EncodedTextLen() const;

        template <typename T>
        T get_EncodedTextLen_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(354);
        }

        template <typename T>
        void set_EncodedTextLen(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(354, val);
        }

        // TransactTime
        bool has_TransactTime() const;
        std::string_view get_TransactTime() const;
        void set_timestamp_TransactTime();
        // EncodedText
        bool has_EncodedText() const;
        const char* get_EncodedText() const;
        void set_EncodedText(const char*, std::size_t);
    private:
        llfix::OutgoingFixMessage* m_outgoing_message_instance = nullptr;
        const llfix::IncomingFixMessage* m_incoming_message_instance = nullptr;
};

} // namespace

} // namespace