/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cassert>
#include <cstdint>
#include <cstddef>
#include <string_view>

#include <llfix/incoming_fix_message.h>
#include <llfix/outgoing_fix_message.h>

namespace custom
{

namespace FIX44
{

class OrderCancelReplaceRequest
{
    public:
        explicit OrderCancelReplaceRequest(llfix::OutgoingFixMessage*);
        explicit OrderCancelReplaceRequest(const llfix::IncomingFixMessage*);

        llfix::OutgoingFixMessage* outgoing_message();

        void set_msg_type(char);
        void set_msg_type(const std::string_view&);

        // HandlInst
        bool has_HandlInst() const;
        char get_HandlInst() const;
        void set_HandlInst(char);
        // Side
        bool has_Side() const;
        char get_Side() const;
        void set_Side(char);
        // OrdType
        bool has_OrdType() const;
        char get_OrdType() const;
        void set_OrdType(char);
        // TimeInForce
        bool has_TimeInForce() const;
        char get_TimeInForce() const;
        void set_TimeInForce(char);
        // OrderCapacity
        bool has_OrderCapacity() const;
        char get_OrderCapacity() const;
        void set_OrderCapacity(char);
        // PartyIDSource
        bool has_PartyIDSource() const;
        char get_PartyIDSource() const;
        void set_PartyIDSource(char);
        // OptAttribute
        bool has_OptAttribute() const;
        char get_OptAttribute() const;
        void set_OptAttribute(char);
        // OrderID
        bool has_OrderID() const;
        std::string_view get_OrderID() const;
        void set_OrderID(const std::string_view&);
        // OrigClOrdID
        bool has_OrigClOrdID() const;
        std::string_view get_OrigClOrdID() const;
        void set_OrigClOrdID(const std::string_view&);
        // ClOrdID
        bool has_ClOrdID() const;
        std::string_view get_ClOrdID() const;
        void set_ClOrdID(const std::string_view&);
        // SecondaryClOrdID
        bool has_SecondaryClOrdID() const;
        std::string_view get_SecondaryClOrdID() const;
        void set_SecondaryClOrdID(const std::string_view&);
        // ClOrdLinkID
        bool has_ClOrdLinkID() const;
        std::string_view get_ClOrdLinkID() const;
        void set_ClOrdLinkID(const std::string_view&);
        // ListID
        bool has_ListID() const;
        std::string_view get_ListID() const;
        void set_ListID(const std::string_view&);
        // Account
        bool has_Account() const;
        std::string_view get_Account() const;
        void set_Account(const std::string_view&);
        // SettlDate
        bool has_SettlDate() const;
        std::string_view get_SettlDate() const;
        void set_SettlDate(const std::string_view&);
        // ExecInst
        bool has_ExecInst() const;
        std::string_view get_ExecInst() const;
        void set_ExecInst(const std::string_view&);
        // ExDestination
        bool has_ExDestination() const;
        std::string_view get_ExDestination() const;
        void set_ExDestination(const std::string_view&);
        // Currency
        bool has_Currency() const;
        std::string_view get_Currency() const;
        void set_Currency(const std::string_view&);
        // Text
        bool has_Text() const;
        std::string_view get_Text() const;
        void set_Text(const std::string_view&);
        // PartyID
        bool has_PartyID() const;
        std::string_view get_PartyID() const;
        void set_PartyID(const std::string_view&);
        // Symbol
        bool has_Symbol() const;
        std::string_view get_Symbol() const;
        void set_Symbol(const std::string_view&);
        // SymbolSfx
        bool has_SymbolSfx() const;
        std::string_view get_SymbolSfx() const;
        void set_SymbolSfx(const std::string_view&);
        // SecurityID
        bool has_SecurityID() const;
        std::string_view get_SecurityID() const;
        void set_SecurityID(const std::string_view&);
        // SecurityIDSource
        bool has_SecurityIDSource() const;
        std::string_view get_SecurityIDSource() const;
        void set_SecurityIDSource(const std::string_view&);
        // CFICode
        bool has_CFICode() const;
        std::string_view get_CFICode() const;
        void set_CFICode(const std::string_view&);
        // SecurityType
        bool has_SecurityType() const;
        std::string_view get_SecurityType() const;
        void set_SecurityType(const std::string_view&);
        // SecuritySubType
        bool has_SecuritySubType() const;
        std::string_view get_SecuritySubType() const;
        void set_SecuritySubType(const std::string_view&);
        // MaturityMonthYear
        bool has_MaturityMonthYear() const;
        std::string_view get_MaturityMonthYear() const;
        void set_MaturityMonthYear(const std::string_view&);
        // MaturityDate
        bool has_MaturityDate() const;
        std::string_view get_MaturityDate() const;
        void set_MaturityDate(const std::string_view&);
        // CouponPaymentDate
        bool has_CouponPaymentDate() const;
        std::string_view get_CouponPaymentDate() const;
        void set_CouponPaymentDate(const std::string_view&);
        // IssueDate
        bool has_IssueDate() const;
        std::string_view get_IssueDate() const;
        void set_IssueDate(const std::string_view&);
        // RepoCollateralSecurityType
        bool has_RepoCollateralSecurityType() const;
        std::string_view get_RepoCollateralSecurityType() const;
        void set_RepoCollateralSecurityType(const std::string_view&);
        // CreditRating
        bool has_CreditRating() const;
        std::string_view get_CreditRating() const;
        void set_CreditRating(const std::string_view&);
        // InstrRegistry
        bool has_InstrRegistry() const;
        std::string_view get_InstrRegistry() const;
        void set_InstrRegistry(const std::string_view&);
        // CountryOfIssue
        bool has_CountryOfIssue() const;
        std::string_view get_CountryOfIssue() const;
        void set_CountryOfIssue(const std::string_view&);
        // StateOrProvinceOfIssue
        bool has_StateOrProvinceOfIssue() const;
        std::string_view get_StateOrProvinceOfIssue() const;
        void set_StateOrProvinceOfIssue(const std::string_view&);
        // LocaleOfIssue
        bool has_LocaleOfIssue() const;
        std::string_view get_LocaleOfIssue() const;
        void set_LocaleOfIssue(const std::string_view&);
        // RedemptionDate
        bool has_RedemptionDate() const;
        std::string_view get_RedemptionDate() const;
        void set_RedemptionDate(const std::string_view&);
        // StrikeCurrency
        bool has_StrikeCurrency() const;
        std::string_view get_StrikeCurrency() const;
        void set_StrikeCurrency(const std::string_view&);
        // SecurityExchange
        bool has_SecurityExchange() const;
        std::string_view get_SecurityExchange() const;
        void set_SecurityExchange(const std::string_view&);
        // Issuer
        bool has_Issuer() const;
        std::string_view get_Issuer() const;
        void set_Issuer(const std::string_view&);
        // SecurityDesc
        bool has_SecurityDesc() const;
        std::string_view get_SecurityDesc() const;
        void set_SecurityDesc(const std::string_view&);
        // Pool
        bool has_Pool() const;
        std::string_view get_Pool() const;
        void set_Pool(const std::string_view&);
        // ContractSettlMonth
        bool has_ContractSettlMonth() const;
        std::string_view get_ContractSettlMonth() const;
        void set_ContractSettlMonth(const std::string_view&);
        // CPRegType
        bool has_CPRegType() const;
        std::string_view get_CPRegType() const;
        void set_CPRegType(const std::string_view&);
        // DatedDate
        bool has_DatedDate() const;
        std::string_view get_DatedDate() const;
        void set_DatedDate(const std::string_view&);
        // InterestAccrualDate
        bool has_InterestAccrualDate() const;
        std::string_view get_InterestAccrualDate() const;
        void set_InterestAccrualDate(const std::string_view&);
        // MinQty
        bool has_MinQty() const;

        template <typename T>
        T get_MinQty_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(110, decimal_points);
        }

        template <typename T>
        void set_MinQty(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(110, val, decimal_points);
        }

        // MaxFloor
        bool has_MaxFloor() const;

        template <typename T>
        T get_MaxFloor_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(111, decimal_points);
        }

        template <typename T>
        void set_MaxFloor(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(111, val, decimal_points);
        }

        // Price
        bool has_Price() const;

        template <typename T>
        T get_Price_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(44, decimal_points);
        }

        template <typename T>
        void set_Price(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(44, val, decimal_points);
        }

        // StopPx
        bool has_StopPx() const;

        template <typename T>
        T get_StopPx_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(99, decimal_points);
        }

        template <typename T>
        void set_StopPx(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(99, val, decimal_points);
        }

        // MaxShow
        bool has_MaxShow() const;

        template <typename T>
        T get_MaxShow_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(210, decimal_points);
        }

        template <typename T>
        void set_MaxShow(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(210, val, decimal_points);
        }

        // RepurchaseRate
        bool has_RepurchaseRate() const;

        template <typename T>
        T get_RepurchaseRate_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(227, decimal_points);
        }

        template <typename T>
        void set_RepurchaseRate(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(227, val, decimal_points);
        }

        // Factor
        bool has_Factor() const;

        template <typename T>
        T get_Factor_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(228, decimal_points);
        }

        template <typename T>
        void set_Factor(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(228, val, decimal_points);
        }

        // StrikePrice
        bool has_StrikePrice() const;

        template <typename T>
        T get_StrikePrice_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(202, decimal_points);
        }

        template <typename T>
        void set_StrikePrice(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(202, val, decimal_points);
        }

        // ContractMultiplier
        bool has_ContractMultiplier() const;

        template <typename T>
        T get_ContractMultiplier_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(231, decimal_points);
        }

        template <typename T>
        void set_ContractMultiplier(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(231, val, decimal_points);
        }

        // CouponRate
        bool has_CouponRate() const;

        template <typename T>
        T get_CouponRate_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(223, decimal_points);
        }

        template <typename T>
        void set_CouponRate(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(223, val, decimal_points);
        }

        // OrderQty
        bool has_OrderQty() const;

        template <typename T>
        T get_OrderQty_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(38, decimal_points);
        }

        template <typename T>
        void set_OrderQty(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(38, val, decimal_points);
        }

        // CashOrderQty
        bool has_CashOrderQty() const;

        template <typename T>
        T get_CashOrderQty_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(152, decimal_points);
        }

        template <typename T>
        void set_CashOrderQty(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(152, val, decimal_points);
        }

        // OrderPercent
        bool has_OrderPercent() const;

        template <typename T>
        T get_OrderPercent_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(516, decimal_points);
        }

        template <typename T>
        void set_OrderPercent(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(516, val, decimal_points);
        }

        // RoundingModulus
        bool has_RoundingModulus() const;

        template <typename T>
        T get_RoundingModulus_as(std::size_t decimal_points=0) const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(469, decimal_points);
        }

        template <typename T>
        void set_RoundingModulus(T val, std::size_t decimal_points=0)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(469, val, decimal_points);
        }

        // PriceType
        bool has_PriceType() const;

        template <typename T>
        T get_PriceType_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(423);
        }

        template <typename T>
        void set_PriceType(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(423, val);
        }

        // EncodedTextLen
        bool has_EncodedTextLen() const;

        template <typename T>
        T get_EncodedTextLen_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(354);
        }

        template <typename T>
        void set_EncodedTextLen(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(354, val);
        }

        // NoPartyIDs
        bool has_NoPartyIDs() const;

        template <typename T>
        T get_NoPartyIDs_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(453);
        }

        template <typename T>
        void set_NoPartyIDs(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(453, val);
        }

        // PartyRole
        bool has_PartyRole() const;

        template <typename T>
        T get_PartyRole_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(452);
        }

        template <typename T>
        void set_PartyRole(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(452, val);
        }

        // RepurchaseTerm
        bool has_RepurchaseTerm() const;

        template <typename T>
        T get_RepurchaseTerm_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(226);
        }

        template <typename T>
        void set_RepurchaseTerm(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(226, val);
        }

        // EncodedIssuerLen
        bool has_EncodedIssuerLen() const;

        template <typename T>
        T get_EncodedIssuerLen_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(348);
        }

        template <typename T>
        void set_EncodedIssuerLen(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(348, val);
        }

        // EncodedSecurityDescLen
        bool has_EncodedSecurityDescLen() const;

        template <typename T>
        T get_EncodedSecurityDescLen_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(350);
        }

        template <typename T>
        void set_EncodedSecurityDescLen(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(350, val);
        }

        // TransactTime
        bool has_TransactTime() const;
        std::string_view get_TransactTime() const;
        void set_timestamp_TransactTime();
        // EncodedText
        bool has_EncodedText() const;
        const char* get_EncodedText() const;
        void set_EncodedText(const char*, std::size_t);
        // EncodedIssuer
        bool has_EncodedIssuer() const;
        const char* get_EncodedIssuer() const;
        void set_EncodedIssuer(const char*, std::size_t);
        // EncodedSecurityDesc
        bool has_EncodedSecurityDesc() const;
        const char* get_EncodedSecurityDesc() const;
        void set_EncodedSecurityDesc(const char*, std::size_t);
    private:
        llfix::OutgoingFixMessage* m_outgoing_message_instance = nullptr;
        const llfix::IncomingFixMessage* m_incoming_message_instance = nullptr;
};

} // namespace

} // namespace