/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cassert>
#include <cstdint>
#include <cstddef>
#include <string_view>

#include <llfix/incoming_fix_message.h>
#include <llfix/outgoing_fix_message.h>

namespace custom
{

namespace FIX44
{

class Reject
{
    public:
        explicit Reject(llfix::OutgoingFixMessage*);
        explicit Reject(const llfix::IncomingFixMessage*);

        llfix::OutgoingFixMessage* outgoing_message();

        void set_msg_type(char);
        void set_msg_type(const std::string_view&);

        // RefMsgType
        bool has_RefMsgType() const;
        std::string_view get_RefMsgType() const;
        void set_RefMsgType(const std::string_view&);
        // Text
        bool has_Text() const;
        std::string_view get_Text() const;
        void set_Text(const std::string_view&);
        // RefSeqNum
        bool has_RefSeqNum() const;

        template <typename T>
        T get_RefSeqNum_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(45);
        }

        template <typename T>
        void set_RefSeqNum(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(45, val);
        }

        // RefTagID
        bool has_RefTagID() const;

        template <typename T>
        T get_RefTagID_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(371);
        }

        template <typename T>
        void set_RefTagID(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(371, val);
        }

        // SessionRejectReason
        bool has_SessionRejectReason() const;

        template <typename T>
        T get_SessionRejectReason_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(373);
        }

        template <typename T>
        void set_SessionRejectReason(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(373, val);
        }

        // EncodedTextLen
        bool has_EncodedTextLen() const;

        template <typename T>
        T get_EncodedTextLen_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(354);
        }

        template <typename T>
        void set_EncodedTextLen(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(354, val);
        }

        // EncodedText
        bool has_EncodedText() const;
        const char* get_EncodedText() const;
        void set_EncodedText(const char*, std::size_t);
    private:
        llfix::OutgoingFixMessage* m_outgoing_message_instance = nullptr;
        const llfix::IncomingFixMessage* m_incoming_message_instance = nullptr;
};

} // namespace

} // namespace