/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cassert>
#include <cstdint>
#include <cstddef>
#include <string_view>

#include <llfix/incoming_fix_message.h>
#include <llfix/outgoing_fix_message.h>

namespace custom
{

namespace FIX44
{

class ResendRequest
{
    public:
        explicit ResendRequest(llfix::OutgoingFixMessage*);
        explicit ResendRequest(const llfix::IncomingFixMessage*);

        llfix::OutgoingFixMessage* outgoing_message();

        void set_msg_type(char);
        void set_msg_type(const std::string_view&);

        // BeginSeqNo
        bool has_BeginSeqNo() const;

        template <typename T>
        T get_BeginSeqNo_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(7);
        }

        template <typename T>
        void set_BeginSeqNo(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(7, val);
        }

        // EndSeqNo
        bool has_EndSeqNo() const;

        template <typename T>
        T get_EndSeqNo_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(16);
        }

        template <typename T>
        void set_EndSeqNo(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(16, val);
        }

    private:
        llfix::OutgoingFixMessage* m_outgoing_message_instance = nullptr;
        const llfix::IncomingFixMessage* m_incoming_message_instance = nullptr;
};

} // namespace

} // namespace