/////////////////////////////////////////////////////////////////////
// GENERATED BY LLFIX CODE GENERATOR 1.0.0 @2026-03-01 15:24:46
/////////////////////////////////////////////////////////////////////
#pragma once

#include <cassert>
#include <cstdint>
#include <cstddef>
#include <string_view>

#include <llfix/incoming_fix_message.h>
#include <llfix/outgoing_fix_message.h>

namespace custom
{

namespace FIX44
{

class SequenceReset
{
    public:
        explicit SequenceReset(llfix::OutgoingFixMessage*);
        explicit SequenceReset(const llfix::IncomingFixMessage*);

        llfix::OutgoingFixMessage* outgoing_message();

        void set_msg_type(char);
        void set_msg_type(const std::string_view&);

        // GapFillFlag
        bool has_GapFillFlag() const;
        bool get_GapFillFlag() const;
        void set_GapFillFlag(bool);
        // NewSeqNo
        bool has_NewSeqNo() const;

        template <typename T>
        T get_NewSeqNo_as() const
        {
            assert(m_incoming_message_instance);
            return m_incoming_message_instance->get_tag_value_as<T>(36);
        }

        template <typename T>
        void set_NewSeqNo(T val)
        {
            assert(m_outgoing_message_instance);
            m_outgoing_message_instance->set_tag(36, val);
        }

    private:
        llfix::OutgoingFixMessage* m_outgoing_message_instance = nullptr;
        const llfix::IncomingFixMessage* m_incoming_message_instance = nullptr;
};

} // namespace

} // namespace